pod-security/restricted/restrict-volume-types.yaml

Signed-off-by: Shuting Zhao <shutting06@gmail.com>

Update cephFS to cephfs

---

pod-security/restricted/require-non-root-groups.yaml
pod-security/tests/default/test-disallow-proc-mount.yaml

fix comments

---

best-practices/restrict_image_registries.yaml
best-practices/restrict_node_port.yaml

fix best practices

---

pod-security/default/disallow-proc-mount/disallow-proc-mount.yaml

add disallow-proc-mount.yaml

---

other/restrict_pod_count_per_node.yaml

Signed-off-by: Shuting Zhao <shutting06@gmail.com>

Add sample policy restrict-pod-count-per-node

---

other/restrict_ingress_host.yaml

add sample for unique ingress host names

---

best-practices/disallow_default_namespace/disallow_default_namespace.yaml
best-practices/disallow_helm_tiller/disallow_helm_tiller.yaml
best-practices/disallow_latest_tag/disallow_latest_tag.yaml
best-practices/require_drop_all/require_drop_all.yaml
best-practices/require_labels/require_labels.yaml
best-practices/require_probes/require_probes.yaml
best-practices/require_ro_rootfs/require_ro_rootfs.yaml
best-practices/restrict_image_registries/restrict_image_registries.yaml
best-practices/restrict_node_port/restrict_node_port.yaml
other/add_nodeSelector.yaml
other/add_volume_deployment.yaml
other/restrict_ingress_host.yaml
other/restrict_pod_count_per_node.yaml
pod-security/default/disallow-host-ipc/disallow-host-ipc.yaml

Clean and normalize policies. Add "add nodeSelector" policy.

---

best-practices/disallow_helm_tiller/disallow_helm_tiller.yaml

fix category

---

other/add_labels.yaml
other/disallow_secrets_from_env_vars.yaml
other/exclude_namespaces_dynamically.yaml
other/require_image_checksum.yaml

Closes #37 
Closes #43 
Closes #18 
Closes #44 
This PR adds three new sample policies and updates an existing one with a new rule.

add new sample policies

---

other/block_updates_deletes.yaml
other/restrict_controlplane_scheduling.yaml
other/sync_secrets.yaml

Closes #48 
Closes #46 
Closes #45 
Adds two new sample policies and enhances/fixes an existing policy.

Add new samples; fix sample

---

other/disallow_localhost_services.yaml

add policy blocking localhost ExternalName Service

---

best-practices/require_drop_all/test.yaml

Fix tests for require_drop_all

---

other/add_ndots.yaml
other/replace_image_registry.yaml
other/require_netpol.yaml
other/require_pdb.yaml

Adds four new policies to the library:
* Add Ndots
* Replace Image Registry
* Require NetworkPolicy
* Require PodDisruptionBudget

New policies for 1.3.6

---

pod-security/restricted/require-non-root-groups/resource.yaml
pod-security/restricted/require-non-root-groups/test.yaml

Tests to cover policy supplementalGroups greater 0 

---

cert-manager/limit-dnsnames.yaml
cert-manager/restrict-issuer.yaml
other/add-pod-proxies.yaml
other/block_updates_deletes.yaml
other/ensure_probes_different.yaml
other/memory-requests-equal-limits.yaml
other/unique-ingress-paths.yaml

Closes #73
Closes #71 
Closes #68 
Closes https://github.com/kyverno/kyverno/issues/2086
Closes https://github.com/kyverno/kyverno/issues/2067
Closes https://github.com/kyverno/kyverno/issues/1685

Policy updates

---

best-practices/check_deprecated_apis.yaml
best-practices/require_drop_all/require_drop_all.yaml

Fixes https://github.com/kyverno/policies/issues/80

check_deprecated_apis.yaml

---

best-practices/check_deprecated_apis.yaml

add title and subject

---

other/pod_lifetime_annotation/policy.yaml
other/pod_lifetime_annotation/resources.yaml
other/pod_lifetime_annotation/test.yaml

Signed-off-by: Trey Dockendorf <tdockendorf@osc.edu>
Goes with documentation from here: https://github.com/kyverno/website/pull/241
For this feature: https://github.com/kyverno/kyverno/pull/2214

Add example for duration operator

---

README.md
other/pod_lifetime_annotation/enforce_pod_duration.yaml
other/pod_lifetime_annotation/test.yaml

Fixes name of user-contributed policy and incorporates that as a note in the README for future.

Fix policy name

---

best-practices/disallow-empty-ingress-host/disallow_empty_ingress_host.yaml
best-practices/disallow-empty-ingress-host/resource.yaml
best-practices/disallow-empty-ingress-host/test.yaml

Signed-off-by: Anita-ihuman <charlesanita403@gmail.com>

 Create policy for disallow empty ingress host

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/sample_policy.md
.github/PULL_REQUEST_TEMPLATE.md
.github/config.yaml
best-practices/disallow-empty-ingress-host/test.yaml

Signed-off-by: Anita-ihuman <charlesanita403@gmail.com>
This PR is a fix for issue #115

created  issue template and enabled welcome bot

---

best-practices/disallow-empty-ingress-host/disallow_empty_ingress_host.yaml

Adds missing annotations to a policy.

add annotations to "disallow empty ingress host"

---

other/restrict_ingress_host/resource.yaml
other/restrict_ingress_host/test.yaml
other/restrict_ingress_host/values.yaml

Signed-off-by: viveksahu26 <vivekkumarsahu650@gmail.com>
#136 
`bug`
kyverno-cli was failing test case for validate policy. Fixed it by making small changes in the test.yaml file and values.yaml file.
- [✓] I have read the [contributing guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md).
- [✓] I have added tests that prove my fix is effective or that my feature works.
- [✓] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding proof manifests to this PR.

fixed test.yaml file and values.yaml file

---

other/disallow_localhost_services/test.yaml

Fixes https://github.com/kyverno/policies/issues/139
1.5
/kind bug

update results to match new policy rule status (skip) logic

---

other/disallow_localhost_services/test.yaml

Signed-off-by: NoSkillGirl <singhpooja240393@gmail.com>
updated no-localhost-service test file
- [] I have read the [contributing guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md).
- [] I have added tests that prove my fix is effective or that my feature works.
- [] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding proof manifests to this PR.

updated no-localhost-service policy

---

other/restrict_secrets_by_name/resource.yaml
other/restrict_secrets_by_name/restrict-secrets-by-name.yaml
other/restrict_secrets_by_name/test.yaml
other/restrict_secrets_by_name/values.yaml

Adds a new sample policy for restricting secrets by name.

add restrict-secrets-by-name

---

best-practices/nginx-custom-snippets/disallow-custom-snippets.yaml
best-practices/nginx-custom-snippets/resources.yaml
best-practices/require_drop_all/require_drop_all.yaml
best-practices/require_drop_cap_net_raw/require_drop_cap_net_raw.yaml
other/add_env_vars_from_cm/add-env-vars-from-cm.yaml
other/add_env_vars_from_cm/patchedResource01.yaml
other/add_env_vars_from_cm/resource.yaml
other/add_env_vars_from_cm/test.yaml
other/prepend_image_registry/patchedResource01.yaml
other/prepend_image_registry/patchedResource02.yaml
other/prepend_image_registry/prepend_image_registry.yaml
other/prepend_image_registry/resource.yaml
other/prepend_image_registry/test.yaml
other/prepend_image_registry/values.yaml

Adds:
* Prepend Image Registry (with test files, currently non-functional). Closes #158 
* Add Environment Variables from ConfigMap. Closes #159 
Fixes:
* Drop CAP_NET_RAW (fixes #161 )
* Misspelling in nginx snippets policy (fixes #162 )
* Drop ALL (fixes #163 )

add sample policies

---

other/add-pod-proxies/patchedResource2.yaml
other/add-pod-proxies/resource.yaml

Signed-off-by: ShutingZhao <shutting06@gmail.com>
Fix patched resource for `add-pod-procies`: add missing name.
- [] I have added tests that prove my fix is effective or that my feature works.
cc @viveksahu26

fix add-pod-procies: add missing name

---

other/protect_node_taints/protect-node-taints.yaml

Adds a new sample policy "Protect Node Taints" which closes #168

Add protect node taints policy

---

other/allowed_pod_priorities/allowed_pod_priorities.yaml
other/exclude_namespaces_dynamically.yaml

Issue [2689 ](https://github.com/kyverno/kyverno/issues/2689) and discussion [2690](https://github.com/kyverno/kyverno/discussions/2690).
/kind bug
This PR updates two policies to use `request.namespace` for deriving the Namespace of an object as a replacement for the less optimal (and problematic) `request.object.metadata.namespace`. This actually fixes the policies to work properly for higher-level Pod controllers whereas the were silently broken (and apparently untested).
- [] I have added tests that prove my fix is effective or that my feature works.
- [] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and …

change any namespace vars to request.namespace

---

other/allowed_pod_priorities/values.yaml

Fixes https://github.com/kyverno/policies/pull/170 which didn't contain the `request.namespace` variable in the values file. My bad.
- [] I have read the [contributing guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md).
- [] I have added tests that prove my fix is effective or that my feature works.
- [] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding proof manifests to this PR.

add vars so tests pass

---

.github/PULL_REQUEST_TEMPLATE.md

n/a
n/a
/kind cleanup
tidy up the pr template markdown so the checkboxes render
n/a

fix pr template markdown

---

other/disallow_hostprocess/disallow_hostprocess.yaml
other/mitigate_log4shell/mitigate_log4shell.yaml

add log4shell mitigation policy and PSS hostProcess policy

---

other/add-imagepullsecrets-for-containers-and-initcontainers.yaml

> /kind bug
The way it was before it did not work. As per documentation https://kyverno.io/docs/writing-policies/variables/#variables-from-container-images the registry does not have any characters after the hostname.

Fix add-imagepullsecrets-for-containers-and-initcontainers

---

other/require_unique_uid_per_workload/resource.yaml
other/require_unique_uid_per_workload/test.yaml
other/require_unique_uid_per_workload/variables.yaml

adds tests for require_unique_uid_per_workload policy

---

other/add_certificates_volume/add_certificates_volume.yaml
other/check_serviceaccount/check_serviceaccount.yaml
other/check_serviceaccount/resource.yaml
other/check_serviceaccount/test.yaml
other/check_serviceaccount/values.yaml
other/mitigate_log4shell/mitigate_log4shell.yaml

Fixes #209 
Closes #211 
* Adds notes and description to user policy
* Adds new policy

Policy fixes and new

---

other/add_certificates_volume/add_certificates_volume.yaml

Mutate tests fail as cronjob does not support this template
1.6
/kind bug
Add autogen controllers, except cronjob
- [ x] I have read the [contributing guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md).
- [ x] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding proof manifests to this PR.

add autogen controllers - except CronJob

---

other/allowed_pod_priorities/values.yaml

https://github.com/kyverno/kyverno/issues/1933
/milestone 1.6.0
/kind feature

[ CLI ] Add values for deny autogen rules test command

---

other/prepend_image_registry/failpatchedResource.yaml
other/prepend_image_registry/kyverno-test.yaml
other/prepend_image_registry/patchedResourceWithoutInitContainer.yaml
other/prepend_image_registry/resourceFailed.yaml
other/prepend_image_registry/values.yaml
other/prepend_image_registry/withoutinitcontainer.yaml

Signed-off-by: Vyankatesh vyankateshkd@gmail.com
closes https://github.com/kyverno/kyverno/issues/2913
milestone 1.6.0
> /kind bug

Add test-case for foreach prepend-image-registry policy

---

best-practices/require_drop_all/kyverno-test.yaml
best-practices/require_drop_all/resource.yaml
best-practices/require_drop_all/values.yaml
best-practices/require_drop_cap_net_raw/kyverno-test.yaml
best-practices/require_drop_cap_net_raw/resource.yaml
best-practices/require_drop_cap_net_raw/values.yaml

Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>
`/milestone 1.6.0`.
> /kind feature
- Update require-drop-cap policy with drop securityContext capabilities
- Update require_drop_cap_net_raw policy with drop securityContext capabilities
```
$ kyverno-cli test require_drop_all
Executing require_drop_all...
applying 1 policy to 1 resource... 
│───│───────────────────────│───────────────────────────────│──────────────────────────────│────────│
│ # │ POLICY                │ RULE                          │ RESOURCE                     │ RESULT │
│───│───────────────────────│───────────────────────────────│──────────────────────────────│────────│
│ 1 │ drop-all-capabilities │ check-for-drop-initcontainers │ default/Pod/add-capabilities │ Pass   │
│ 2 │ drop-all-capabilities │ …
```

update securityContext drop capabilities policies

---

other/add-image-as-env-var/patchedResource.yaml
other/add-image-as-env-var/resource.yaml
other/add_node_affinity/patchedResource.yaml
other/add_node_affinity/resource.yaml
other/add_volume_deployment/add_volume_deployment.yaml
other/allowed_pod_priorities/allowed_pod_priorities.yaml
other/allowed_pod_priorities/priorityClass.yaml
other/allowed_pod_priorities/resource.yaml
other/block-velero-restore/block-velero-restore.yaml
other/block_updates_deletes/block_updates_deletes.yaml
other/check_serviceaccount/foo-sa.yaml
other/create_pod_antiaffinity/create_pod_antiaffinity.yaml

Signed-off-by: Mritunjay Sharma <mritunjaysharma394@gmail.com>
* Just updates the policies and provides missing resources in some of them
* Also updates some policies with valid any/all usage in preconditions and conditions
/milestone 1.6.0
/kind cleanup
Updates the policies in policy/others and provides missing resources in some of them and lso updates some policies with valid any/all usage in preconditions and conditions

updates policies and resources for kyverno-1.6.0

---

other/ensure_probes_different/ensure_probes_different.yaml
other/ensure_readonly_hostpath/ensure_readonly_hostpath.yaml
other/limit-hostpath-vols/limit-hostpath-vols.yaml
other/memory-requests-equal-limits/memory-requests-equal-limits.yaml
other/pod_lifetime_annotation/enforce_pod_duration.yaml
other/require_unique_external_dns/require_unique_external_dns.yaml
other/require_unique_uid_per_workload/require_unique_uid_per_workload.yaml

Signed-off-by: Abhinav Sinha <abhinav@nirmata.com>
`/milestone 1.6.0`
`/kind enhancement`

Update policies with `preconditions` and `deny.conditions`

---

other/unique-ingress-paths.yaml

Signed-off-by: Vyankatesh vyankateshkd@gmail.com
closes https://github.com/kyverno/kyverno/issues/3087
milestone 1.6.0
> /kind bug

fix unique-ingress-paths policy

---

other/add-imagepullsecrets-for-containers-and-initcontainers.yaml
other/block-pod-exec-by-namespace-label.yaml
other/block-pod-exec-by-namespace.yaml
other/block-pod-exec-by-pod-and-container.yaml
other/block-pod-exec-by-pod-label.yaml
other/block-pod-exec-by-pod-name.yaml
other/exclude_namespaces_dynamically.yaml
other/mutate-large-termination-gps.yaml
other/require_imagepullsecrets.yaml
other/require_netpol.yaml
other/require_pdb.yaml
other/restrict_node_label_changes.yaml
other/restrict_node_label_creation.yaml
other/restrict_pod_count_per_node/restrict_pod_count_per_node.yaml
other/restrict_service_account.yaml

Signed-off-by: ShutingZhao <shuting@nirmata.com>
This PR adds any/all tag in `preconditions` and `deny` rules due to https://github.com/kubernetes/kubernetes/issues/107690.
/1.6.0
/enhancement
cc @zeborg @mritunjaysharma394

Add any/all tag in `preconditions` and `deny`

---

other/verify_image_gcpkms.yaml
other/verify_image_k8s.yaml

feat: add two new verify image policies

---

pod-security/baseline/kustomization.yaml
pod-security/kustomization.yaml
pod-security/restricted/kustomization.yaml

Fixes #258 
Restore Kustomize files to PSS policies.

Restore Kustomize files

---

other/restrict_automount_sa_token/restrict_automount_sa_token.yaml

use =() syntax for serviceAccountAutoMountToken

feat: enhance restrict_automount_sa_token

---

other/allowed_label_changes/allowed-label-changes.yaml

Closes #247 
Adds a new sample policy called Allowed Label Changes

add "allowed label changes" policy

---

best-practices/add_safe_to_evict/kyverno-test.yaml
best-practices/add_safe_to_evict/myapp-pod03-patched.yaml
best-practices/add_safe_to_evict/myapp-pod04-patched.yaml
best-practices/add_safe_to_evict/resource.yaml

None
Fixes tests from earlier PR #267 and expands them.

fix, add tests

---

other/limit-configmap-for-sa/kyverno-test.yaml
other/limit-configmap-for-sa/limit_configmap_for_sa.yaml
other/limit-configmap-for-sa/resource.yaml
other/limit-configmap-for-sa/variables.yaml

Signed-off-by: eminaktas <eminaktas34@gmail.com>
Signed-off-by: Emin Aktas <emin.aktas@trendyol.com>
None
Adds a new policy for limiting a ConfigMap.
```bash
~ kubectl kyverno test other/limit-configmap-for-sa             
Executing limit-configmap-for-sa...
applying 1 policy to 2 resources... 
│───│────────────────────────│──────────────────────────────────│───────────────────────────────────────────│────────│
│ # │ POLICY                 │ RULE                             │ RESOURCE                                  │ RESULT │
│───│────────────────────────│──────────────────────────────────│───────────────────────────────────────────│────────│
│ 1 │ limit-configmap-for-sa │ limit-configmap-for-sa-developer │ default/ConfigMap/any-configmap-name-good │ Pass   │
│ 2 │ …
```

add: new policy limit config map for serviceaccount

---

other/block_stale_images/bad.yaml
other/block_stale_images/block-stale-images.yaml
other/block_stale_images/good.yaml

This PR adds a sample policy to check the staleness of an image.

add freshness policy

---

.github/workflows/ci.yml

Addressed https://github.com/kyverno/policies/pull/275#issuecomment-1062861955.

Update versioning comment

---

other/exclude_namespaces_dynamically.yaml

See: https://github.com/kyverno/website/pull/483/files/bb2003763ef5e6bc1e9fd3205075453c2a9768fd..247ebe8cf537147d59e9699e9371d8d735916928#r824663319
Added versions

add versions

---

openshift/README.md
openshift/disallow-deprecated-apis/disallow-deprecated-apis.yaml
openshift/disallow-deprecated-apis/kyverno-test.yaml
openshift/disallow-deprecated-apis/resources.yaml
openshift/disallow-jenkins-pipeline-strategy/disallow-jenkins-pipeline-strategy.yaml
openshift/disallow-jenkins-pipeline-strategy/kyverno-test.yaml
openshift/disallow-jenkins-pipeline-strategy/resources.yaml
openshift/disallow-security-context-constraint-anyuid/disallow-security-context-constraint-anyuid.yaml
openshift/disallow-security-context-constraint-anyuid/kyverno-test.yaml
openshift/disallow-security-context-constraint-anyuid/resources.yaml
openshift/disallow-self-provisioner-binding/disallow-deprecated-apis/disallow-deprecated-apis.yaml
openshift/disallow-self-provisioner-binding/disallow-deprecated-apis/kyverno-test.yaml
openshift/disallow-self-provisioner-binding/disallow-deprecated-apis/resources.yaml
openshift/disallow-self-provisioner-binding/disallow-jenkins-pipeline-strategy/disallow-jenkins-pipeline-strategy.yaml
openshift/disallow-self-provisioner-binding/disallow-jenkins-pipeline-strategy/kyverno-test.yaml
openshift/disallow-self-provisioner-binding/disallow-jenkins-pipeline-strategy/resources.yaml
openshift/disallow-self-provisioner-binding/disallow-security-context-constraint-anyuid/disallow-security-context-constraint-anyuid.yaml
openshift/disallow-self-provisioner-binding/disallow-security-context-constraint-anyuid/kyverno-test.yaml
openshift/disallow-self-provisioner-binding/disallow-security-context-constraint-anyuid/resources.yaml
openshift/disallow-self-provisioner-binding/disallow-self-provisioner-binding.yaml
openshift/disallow-self-provisioner-binding/kyverno-test.yaml
openshift/disallow-self-provisioner-binding/resources.yaml
openshift/disallow-self-provisioner-binding/values.yaml
openshift/enforce-etcd-encryption/enforce-etcd-encryption.yaml
openshift/enforce-etcd-encryption/kyverno-test.yaml
openshift/enforce-etcd-encryption/resources.yaml
openshift/validate-routes/check-routes.yaml
openshift/validate-routes/kyverno-test.yaml
openshift/validate-routes/resources.yaml

Signed-off-by: patelrit <ritesh@nirmata.com>
cherry-pick openshift policies

Add openshift policies

---

other/prevent-cr8escape/kyverno-test.yaml
other/prevent-cr8escape/prevent-cr8escape.yaml
other/prevent-cr8escape/resources.yaml

CVE-2022-0811
Sample policy to restrict characters in sysctls

add sample to restrict sysctl chars

---

best-practices/nginx-custom-snippets/disallow-custom-snippets.yaml
best-practices/nginx_annotation_checks/kyverno-test.yaml
best-practices/nginx_annotation_checks/resources.yaml
best-practices/nginx_annotation_checks/restrict-annotations.yaml
best-practices/nginx_path_checks/kyverno-test.yaml
best-practices/nginx_path_checks/resources.yaml
best-practices/nginx_path_checks/restrict-path.yaml

Fixes https://github.com/kyverno/policies/issues/301
Sample policies to restrict NGINX Ingress annotation values and Ingress host paths

check annotations and paths

---

best-practices/nginx_annotation_checks/restrict-annotations.yaml
best-practices/nginx_path_checks/restrict-path.yaml

add NGINX fix version

---

best-practices/nginx_annotation_checks/restrict-annotations.yaml

fix typo in restrict-annotations policy

---

best-practices/nginx-custom-snippets/disallow-custom-snippets.yaml
best-practices/nginx_annotation_checks/restrict-annotations.yaml
best-practices/nginx_path_checks/restrict-path.yaml
openshift/disallow-deprecated-apis/resources.yaml
other/limit-configmap-for-sa/limit_configmap_for_sa.yaml
other/prevent-cr8escape/prevent-cr8escape.yaml
psp-migration/check_supplemental_groups/check-supplemental-groups.yaml

* Fixes latest NGINX policies
* Restores removed Subjects block removed in #308 
* Fixes minor typos

Policy fixes and updates

---

other/limit-configmap-for-sa/limit_configmap_for_sa.yaml

* Comments out restored Subjects block until fix is in the CLI code

comment out subject block to pass CI

---

karpenter/add-karpenter-donot-evict/add-karpenter-donot-evict.yaml
karpenter/add-karpenter-donot-evict/kyverno-test.yaml
karpenter/add-karpenter-donot-evict/patched01.yaml
karpenter/add-karpenter-donot-evict/patched02.yaml
karpenter/add-karpenter-donot-evict/resource.yaml
other/add-tolerations/add-tolerations.yaml
other/add-tolerations/kyverno-test.yaml
other/add-tolerations/patched01.yaml
other/add-tolerations/patched02.yaml
other/add-tolerations/resource.yaml
other/add-ttl-jobs/add-ttl-jobs.yaml
other/add-ttl-jobs/kyverno-test.yaml
other/add-ttl-jobs/patched01.yaml
other/add-ttl-jobs/resource.yaml

* Adds sample policy to add TTL if missing to Jobs
* Adds sample policy to add Pod tolerations
* Add sample Karpenter policy to add do not evict

Add 3 sample policies with tests

---

psa/add-psa-labels/add-psa-labels.yaml
psa/deny-privileged-profile/deny-privileged-profile.yaml

add 2 PSA policies

---

other/ingress_host_match_tls/ingress-host-match-tls.yaml
other/ingress_host_match_tls/kyverno-test.yaml
other/ingress_host_match_tls/resource.yaml

fixes https://github.com/kyverno/policies/issues/360
- Repair validation of the policy for multiple hosts.
- Add more tests.

fix(ingress-host-match-tls): repair policy and add tests

---

other/inject_env_var_from_image_label/inject-env-var-from-image-label.yaml
other/label_nodes_cri/label-nodes-cri.yaml

Closes #362 
Closes #363 
* Adds 2 new sample policies

Add 2 sample policies

---

other/restrict-binding-clusteradmin/restrict-binding-clusteradmin.yaml

Signed-off-by: dschunack <dschunack@web.de>
restrict-binding-clusteradmin policy is not working correct.
Fixes #365 

Fix issue in restrict-binding-clusteradmin Policy #365

---

other/ingress_host_match_tls/ingress-host-match-tls.yaml

Do the math on real values, skip type errors.

fix(ingress_host_match_tls): skip failure on missing values

---

.github/workflows/ci.yml
linkerd/add_policy_annotation/add-policy-annotation.yaml
other/require-container-port-names/require-container-port-names.yaml

* Bumps Go to 1.18 to fix CI errors
* Adds 2 sample policies (need elaboration)

Bump Go; 2 policies

---

.github/workflows/ci.yml

Signed-off-by: ShutingZhao <shuting@nirmata.com>
Closes https://github.com/kyverno/policies/issues/387.
This PR bumps to Go 1.18.

Bump to Go 1.18

---

psa/add-psa-labels/kyverno-test.yaml
psa/add-psa-labels/patchedResource.yaml
psa/add-psa-labels/patchedResourcefail.yaml
psa/add-psa-labels/resource.yaml
psa/add-psa-labels/resourcefail.yaml

Signed-off-by: Vyankatesh vyankateshkd@gmail.com
Add testcase for add-psa-label policy

Add testcases

---

.github/workflows/ci.yml
aws/require_encryption_aws_loadbalancers/require-encryption-aws-loadbalancers.yaml
other/add_emptydir_sizelimit/add-emptydir-sizelimit.yaml
other/disable_service_discovery/disable-service-discovery.yaml
other/docker_socket_requires_label/docker-socket-requires-label.yaml
other/docker_socket_requires_label/kyverno-test.yaml
other/docker_socket_requires_label/resource.yaml
other/require_vuln_scan/require-vulnerability-scan.yaml
other/restrict_binding_system_groups/restrict-binding-system-groups.yaml

This PR adds many new sample policies:
* Docker Socket Requires Labels (from documentation, with tests)
* Require Image Vulnerability Scans
* Restrict Binding System Groups
* Require Encryption with AWS LoadBalancers
* Disable Service Discovery
* Add emptyDir sizeLimit

New sample policies

---

tekton/block-tekton-task-runs/block-tekton-task-runs.yaml

There might be existing TaskRuns that can be modified with anyone else, so we should block updating them too.
/cc @chipzoller

feat: add update operation to the list

---

best-practices/check_deprecated_apis/check_deprecated_apis.yaml

Signed-off-by: Zadkiel Aharonian <zadkiel_aharonian@carrefour.com>
https://kubernetes.slack.com/archives/CLGR9BJU9/p1663844765023809?thread_ts=1663667273.035559&cid=CLGR9BJU9
Do not throw error event on background apply.

fix(check_deprecated_apis): do not throw error event on background apply

---

linkerd/check-linkerd-authorizationpolicy/check-linkerd-authorizationpolicy.yaml
linkerd/require-linkerd-server/require-linkerd-server.yaml
other/verify_manifest_integrity/verify-manifest-integrity.yaml
pod-security/subrule/baseline/baseline-latest.yaml
pod-security/subrule/restricted/restricted-exclude-capabilities/restricted-exclude-capabilities.yaml
pod-security/subrule/restricted/restricted-exclude-seccomp/restricted-exclude-seccomp.yaml
pod-security/subrule/restricted/restricted-latest/restricted-latest.yaml
psa/add-privileged-existing-namespaces/add-privileged-existing-namespaces.yaml

* Adds Kyverno sample policies for 1.8 features
* 2 more Linkerd policies

Add Kyverno 1.8 sample policies, 2 Linkerd policies

---

other/restrict_binding_system_groups/restrict-binding-system-groups.yaml

Fixes #411 
Fixes the restrict-binding-system-groups policy.

fix restrict-binding-system-groups

---

best-practices/require_drop_all/require_drop_all.yaml
best-practices/require_drop_cap_net_raw/require_drop_cap_net_raw.yaml
pod-security/restricted/disallow-capabilities-strict/disallow-capabilities-strict.yaml

Closes #413 
* Sends `drop[]` and `add[]` policies to `to_upper()` in order to be case insensitive.

send lists to_upper

---

best-practices/check_deprecated_apis/check_deprecated_apis.yaml

Modifies check-deprecated-apis with some additional notes for users and updates for newer policy schema.

modify check-deprecated-apis with notes

---

argo/argo-cluster-generation-from-rancher-capi/argo-cluster-generation-from-rancher-capi.yaml

Fix Argo cluster generation from Rancher to propagate label changes.
Closes #396 
Signed-off-by: ron1 <ron18219@gmail.com>
Fix Argo cluster generation from Rancher to propagate label changes. Prior to this fix, Rancher cluster label changes were not propagated to the corresponding Argo cluster secrets.

Fix Argo cluster generation from Rancher to propagate label changes

---

pod-security/subrule/baseline/kyverno-test.yaml
pod-security/subrule/baseline/resource.yaml
pod-security/subrule/restricted/restricted-exclude-capabilities/kyverno-test.yaml
pod-security/subrule/restricted/restricted-exclude-capabilities/resource.yaml
pod-security/subrule/restricted/restricted-exclude-seccomp/kyverno-test.yaml
pod-security/subrule/restricted/restricted-exclude-seccomp/resource.yaml
pod-security/subrule/restricted/restricted-latest/kyverno-test.yaml
pod-security/subrule/restricted/restricted-latest/resource.yaml

* Adds test cases to existing podSecurity policies and supersedes PR #403 (thank you to @vyankyGH)

add test coverage for podSecurity rules

---

other/allowed-base-images/allowed-base-images.yaml
other/require-base-image/require-base-image.yaml

This PR aims to fix the rule names.
/cc @chipzoller

fix: change rule names

---

kubeops/config-syncer-secret-generation-from-rancher-capi/config-syncer-secret-generation-from-rancher-capi.yaml

Closes #439 
Leverage Preconditions to optimize Kubeops config-syncer-secret-generation-from-rancher-capi

Leverage Preconditions to optimize Kubeops config-syncer-secret-generation-from-rancher-capi #439

---

openshift/disallow-self-provisioner-binding/disallow-self-provisioner-binding.yaml
other/add-imagepullsecrets-for-containers-and-initcontainers/add-imagepullsecrets-for-containers-and-initcontainers.yaml
other/add_certificates_volume/add_certificates_volume.yaml
other/add_default_resources/add-default-resources.yaml
other/advanced_restrict_image_registries/advanced-restrict-image-registries.yaml
other/allowed_pod_priorities/allowed_pod_priorities.yaml
other/block_updates_deletes/block_updates_deletes.yaml
other/enforce_resources_as_ratio/enforce-resources-as-ratio.yaml
other/ensure-production-matches-staging/ensure-production-matches-staging.yaml
other/ensure_readonly_hostpath/ensure_readonly_hostpath.yaml
other/kubernetes_version_check/kubernetes-version-check.yaml
other/limit-configmap-for-sa/limit_configmap_for_sa.yaml
other/limit-hostpath-type-pv/limit_hostpath_type_pv.yaml
other/limit-hostpath-vols/limit-hostpath-vols.yaml
other/nfs-subdir-external-provisioner-storage-path/nfs-subdir-external-provisioner-storage-path.yaml
other/prepend_image_registry/prepend_image_registry.yaml
other/require_emptydir_requests_limits/require-emptydir-requests-limits.yaml
other/require_imagepullsecrets/require_imagepullsecrets.yaml
other/require_unique_external_dns/require_unique_external_dns.yaml
other/require_unique_uid_per_workload/require_unique_uid_per_workload.yaml
other/restrict-service-account/restrict_service_account.yaml
other/restrict_ingress_host/restrict_ingress_host.yaml
other/restrict_secrets_by_name/restrict-secrets-by-name.yaml
psp-migration/check_supplemental_groups/check-supplemental-groups.yaml
velero/block-velero-restore/block-velero-restore.yaml

Fixes #422 
* Fixes the Unique Ingress Host policy to update the old language for new, compatible with 1.6+.
* Updates all policies to remove use of deprecated operators `In` and `NotIn`

Policy fixes

---

other/require-topologyspreadconstraints/kyverno-test.yaml
other/require-topologyspreadconstraints/resource-fail1.yaml
other/require-topologyspreadconstraints/resource-fail2.yaml
other/require-topologyspreadconstraints/resource-fail3.yaml
other/require-topologyspreadconstraints/resource-pass.yaml
other/require-topologyspreadconstraints/resource-skip.yaml
other/require-topologyspreadconstraints/topologyspreadconstraints-policy.yaml

Signed-off-by: André Bauer <andre.bauer@staffbase.com>
https://github.com/kyverno/policies/issues/429
- add topologyspreadconstraints policy
```
kyverno test .
Executing topologyspreadconstraints...
applying 1 policy to 5 resources... 
│───│─────────────│─────────────│──────────────────────────────│────────│
│ # │ POLICY      │ RULE        │ RESOURCE                     │ RESULT │
│───│─────────────│─────────────│──────────────────────────────│────────│
│ 1 │ spread-pods │ spread-pods │ monitoring/StatefulSet/pass  │ Pass   │
│ 2 │ spread-pods │ spread-pods │ monitoring/StatefulSet/fail1 │ Pass   │
│ 3 │ spread-pods │ spread-pods │ monitoring/StatefulSet/fail2 │ Pass   │
│ 4 │ spread-pods │ spread-pods │ monitoring/StatefulSet/fail3 │ Pass   │
│ 5 │ spread-pods │ spread-pods │ …
```

add topologyspreadconstraints policy

---

other/require-opa-env/kyverno-test.yaml
other/require-opa-env/require-opa-enabled.yaml
other/require-opa-env/resource.yaml

Add the check of an env variable.

add require opa env

---

kasten/k10-3-2-1-backup/k10-backup-policy.yaml
other/ingress_host_match_tls/resource.yaml

fix allnotin policy

---

best-practices/add_rolebinding/add_rolebinding.yaml
best-practices/require_probes/require_probes.yaml
other/require_qos_burstable/kyverno-test.yaml
other/require_qos_burstable/require_qos_burstable.yaml
other/require_qos_burstable/resource.yaml
other/require_qos_guaranteed/kyverno-test.yaml
other/require_qos_guaranteed/require_qos_guaranteed.yaml
other/require_qos_guaranteed/resource.yaml
other/require_storageclass/kyverno-test.yaml
other/require_storageclass/require_storageclass.yaml
other/require_storageclass/resource.yaml
other/restrict_networkpolicy_empty_podselector/kyverno-test.yaml
other/restrict_networkpolicy_empty_podselector/resource.yaml
other/restrict_networkpolicy_empty_podselector/restrict_networkpolicy_empty_podselector.yaml
other/restrict_storageclass/kyverno-test.yaml
other/restrict_storageclass/resource.yaml
other/restrict_storageclass/restrict_storageclass.yaml

This PR enhances and adds a number of policies designed to solve more multi-tenancy use cases/concerns based upon the guidance provided on the official Kubernetes multi-tenancy page [here](https://kubernetes.io/docs/concepts/security/multi-tenancy/).

New multi-tenancy policies

---

other/restrict_node_affinity/kyverno-test.yaml
other/restrict_node_affinity/resource.yaml
other/restrict_node_affinity/restrict_node_affinity.yaml

Adds Restrict Node Affinity policy

Add Restrict Node Affinity policy

---

best-practices/check_deprecated_apis/check_deprecated_apis.yaml
best-practices/check_deprecated_apis/kyverno-test.yaml
best-practices/check_deprecated_apis/resource.yaml

This PR adds validation and testing for deprecated apis in kubernetes v1.29

v1.29 deprecated apis validation

---

other/namespace-protection/namespace-protection.yaml

* Adds a dynamic namespace protector policy based on fixes available in 1.9

add namespace-protection

---

other/replace_image_registry/replace_image_registry.yaml

This PR fixes image registry mutation policies.

fix: image registry mutation policies

---

other/restrict_node_selection/restrict_node_selection.yaml

Closes #532 
Further fuxes to disable background mode, add a precondition, and extend description.

further fix restrict node selection

---

other/add-pod-priorityclassname/add-pod-priorityclassname.yaml
other/add-pod-priorityclassname/kyverno-test.yaml
other/restrict_node_selection/restrict_node_selection.yaml

Fixes #530 
Adds rules to cover Pod controllers and minor tweaks.

Fix add-pod-priorityclassname

---

other/pdb-minavailable/kyverno-test.yaml
other/pdb-minavailable/resource.yaml
other/pdb-minavailable/values.yaml

Adds tests for the pdb-minavailable policy

Add tests for pdb-minavailable policy

---

other/check_serviceaccount/check_serviceaccount.yaml
velero/backup-all-volumes/backup-all-volumes.yaml
velero/backup-all-volumes/kyverno-test.yaml
velero/backup-all-volumes/patchedResource-fourth.yaml
velero/backup-all-volumes/patchedResource-third.yaml
velero/backup-all-volumes/patchedResource.yaml
velero/backup-all-volumes/resource.yaml
velero/backup-all-volumes/values.yaml

Closes #516 
* Adds a necessary precondition to an existing policy
* Adds a new Velero policy with tests

Add sample

---

velero/backup-all-volumes/artifacthub-pkg.yml
velero/block-velero-restore/artifacthub-pkg.yml
velero/validate-cron-schedule/artifacthub-pkg.yml

https://github.com/artifacthub/hub/issues/2653#issuecomment-1377723000
#491 
update readme in artifact-pkg.yml files and reflect these changes in artifact hub

Update readme in artifact-pkg.yml files

---

velero/backup-all-volumes/artifacthub-pkg.yml
velero/block-velero-restore/artifacthub-pkg.yml
velero/validate-cron-schedule/artifacthub-pkg.yml

https://github.com/kyverno/policies/pull/545
https://github.com/kyverno/policies/issues/549
Add digest in the artifacthub-pkg.yml, so that it can show updates in policies in artifact hub.

Add digest and make readme visiable in artifact hub

---

.github/ISSUE_TEMPLATE/bug_report.yml

bump dropdown

---

argo/application-field-validation/application-field-validation.yaml
argo/application-field-validation/artifacthub-pkg.yml

Close: https://github.com/kyverno/policies/issues/571
Modify an existing policy, update the digest field in artifacthub-pkg.yml, ensure the update is displayed in Artifact Hub.

Test out the policy change process to ensure it works as expected

---

argo/application-field-validation/application-field-validation.yaml
argo/application-field-validation/artifacthub-pkg.yml

Close: https://github.com/kyverno/policies/issues/574
revert this process (Modify an existing policy, update the digest field in artifacthub-pkg.yml, ensure the update is displayed in Artifact Hub.)

Revert changes in the test out of the policy change process

---

argo/application-field-validation/01-install.yaml
argo/application-field-validation/02-applications.yaml
argo/application-field-validation/README.md
argo/application-field-validation/application.yaml
argo/application-field-validation/crd.yaml
argo/application-field-validation/policy-ready.yaml
argo/application-field-validation/report.yaml
kuttl-test.yaml

#546 
* Initializes kuttl tests with a TestSuite file
* Writes the first test starting in the `Argo` directory

Enable kuttl testing

---

argo/application-field-validation/policy-ready.yaml

* Changes the policy assert file from kind `ClusterPolicy` to `Changed` as a test to confirm this is what is breaking rendering after the last PR merge.

Rename ClusterPolicy to Changed to fix rendering

---

kasten/k10-minimum-retention/artifacthub-pkg.yml
kasten/k10-minimum-retention/k10-minimum-retention.yaml
other/add-emptydir-sizelimit/add-emptydir-sizelimit.yaml
other/add-emptydir-sizelimit/artifacthub-pkg.yml
other/add-volume-deployment/add-volume-deployment.yaml
other/add-volume-deployment/artifacthub-pkg.yml
other/annotate-base-images/annotate-base-images.yaml
other/annotate-base-images/artifacthub-pkg.yml
other/inject-env-var-from-image-label/artifacthub-pkg.yml
other/inject-env-var-from-image-label/inject-env-var-from-image-label.yaml

Fixes and improves some JSON patch policies.

Minor fixes for JSON patch policies

---

.github/workflows/ci.yml

Close: https://github.com/kyverno/policies/issues/578
GitHub Actions step in the [existing ci.yml workflow](https://github.com/kyverno/policies/blob/main/.github/workflows/ci.yml#L21) to validate some of the required items in the policy [Contribution guide](https://github.com/kyverno/policies#contribution). This will fire upon any new PR to kyverno/policies. See examples such as [this one](https://github.com/kyverno/kyverno/blob/main/.github/workflows/cli.yaml#L29-L37).
Policy is located in a folder with no other characters than dashes
Policy is named the same as the folder
The artifacthub-pkg.yml file is found in the same folder as the policy

Update workflow to validate all policies according to the contribution guide 

---

.github/workflows/ci.yml

Close: https://github.com/kyverno/policies/issues/611

Put 'Validate all policies' before 'Test Policy'

---

aws/require-encryption-aws-loadbalancers/01-assert.yaml
aws/require-encryption-aws-loadbalancers/01-enforce.yaml
aws/require-encryption-aws-loadbalancers/02-manifests.yaml
aws/require-encryption-aws-loadbalancers/99-delete.yaml
aws/require-encryption-aws-loadbalancers/service-fail.yaml
aws/require-encryption-aws-loadbalancers/service-pass.yaml
aws/require-encryption-aws-loadbalancers/service-skip.yaml
best-practices/add-network-policy/01-ns.yaml
best-practices/add-network-policy/02-policy.yaml
best-practices/add-network-policy/03-ns.yaml
best-practices/add-network-policy/04-npolicy.yaml
best-practices/add-network-policy/notGeneratedResource.yaml
best-practices/add-network-policy/old-resource.yaml
best-practices/add-network-policy/policy-ready.yaml
best-practices/add-networkpolicy-dns/01-ns.yaml
best-practices/add-networkpolicy-dns/02-policy.yaml
best-practices/add-networkpolicy-dns/03-ns.yaml
best-practices/add-networkpolicy-dns/04-npolicy.yaml
best-practices/add-networkpolicy-dns/generatedResource.yaml
best-practices/add-networkpolicy-dns/notGeneratedResource.yaml
best-practices/add-networkpolicy-dns/old-resource.yaml
best-practices/add-networkpolicy-dns/policy-ready.yaml
best-practices/add-networkpolicy-dns/resource.yaml
best-practices/add-ns-quota/01-ns.yaml
best-practices/add-ns-quota/02-policy.yaml
best-practices/add-ns-quota/03-ns.yaml
best-practices/add-ns-quota/04-npolicy.yaml
best-practices/add-ns-quota/notGeneratedResource.yaml
best-practices/add-ns-quota/old-resource.yaml
best-practices/add-ns-quota/policy-ready.yaml

Kuttl Tests for 
* `require-encryption-aws-loadbalancers`
* `add-networkpolicy`
* `add-networkpolicy-dns`
* `add-ns-quota`

test: aws, best-practices

---

README.md
other/ingress-host-match-tls/artifacthub-pkg.yml
other/ingress-host-match-tls/ingress-host-match-tls.yaml
other/limit-containers-per-pod/artifacthub-pkg.yml
other/limit-containers-per-pod/limit-containers-per-pod.yaml
other/pdb-minavailable/artifacthub-pkg.yml
other/pdb-minavailable/pdb-minavailable.yaml
other/restrict-ingress-host/artifacthub-pkg.yml
other/restrict-ingress-host/restrict-ingress-host.yaml
other/scale-deployment-zero/artifacthub-pkg.yml
other/scale-deployment-zero/scale-deployment-zero.yaml
other/unique-ingress-paths/artifacthub-pkg.yml
other/unique-ingress-paths/unique-ingress-paths.yaml
pod-security/baseline/disallow-capabilities/artifacthub-pkg.yml
pod-security/baseline/disallow-capabilities/disallow-capabilities.yaml
pod-security/restricted/restrict-volume-types/artifacthub-pkg.yml
pod-security/restricted/restrict-volume-types/restrict-volume-types.yaml

* Updates contribution guidelines with more details
* Updates select policies to also match on UPDATE operations
* Updates a couple PSS policies which use `deny` rules to standardize on preconditions which ignore DELETE operations (this is a complementary change from PR https://github.com/kyverno/kyverno/pull/7457)
* Updates the Scale Deployment to Zero policy to account for all containers in a Pod (originally written in PR #476)

Update select policies to add UPDATE op

---

other/add-default-resources/kyverno-test.yaml

This PR reverts changes from #637.

fix: revert changes from #637

---

CRDs/openshift.yaml
openshift/check-routes/01-policy.yaml
openshift/check-routes/02-resources.yaml
openshift/check-routes/policy-ready.yaml
openshift/check-routes/route-bad.yaml
openshift/check-routes/route-good.yaml
openshift/disallow-security-context-constraint-anyuid/01-policy.yaml
openshift/disallow-security-context-constraint-anyuid/02-resources.yaml
openshift/disallow-security-context-constraint-anyuid/clusterroles-bad.yaml
openshift/disallow-security-context-constraint-anyuid/clusterroles-good.yaml
openshift/disallow-security-context-constraint-anyuid/crb-bad.yaml
openshift/disallow-security-context-constraint-anyuid/crb-good.yaml
openshift/disallow-security-context-constraint-anyuid/policy-ready.yaml
openshift/disallow-security-context-constraint-anyuid/rb-bad.yaml
openshift/disallow-security-context-constraint-anyuid/rb-good.yaml
openshift/disallow-security-context-constraint-anyuid/roles-bad.yaml
openshift/disallow-security-context-constraint-anyuid/roles-good.yaml
openshift/disallow-self-provisioner-binding/01-policy.yaml
openshift/disallow-self-provisioner-binding/02-crb.yaml
openshift/disallow-self-provisioner-binding/03-resources.yaml
openshift/disallow-self-provisioner-binding/crb-bad-roleref.yaml
openshift/disallow-self-provisioner-binding/crb-bad-sub-update.yaml
openshift/disallow-self-provisioner-binding/crb-good.yaml
openshift/disallow-self-provisioner-binding/policy-ready.yaml

#546 
3 kuttl tests for Openshift.

tests: openshift 3 tests

---

.github/workflows/test.yml

Fixes #647 
Gets the kyverno kuttl tool from main, instead of a predefined version.

feat: kyverno-kuttl from main

---

istio/create-authorizationpolicy/01-assert.yaml
istio/create-authorizationpolicy/02-clusterrole.yaml
istio/create-authorizationpolicy/04-policy.yaml
istio/create-authorizationpolicy/05-ns.yaml
istio/create-authorizationpolicy/06-assert.yaml
istio/create-authorizationpolicy/policy-ready.yaml

[kyverno#7618](https://github.com/kyverno/kyverno/issues/7618)
Adding back the `create-authorizationpolicy` test as [kyverno#7628](https://github.com/kyverno/kyverno/pull/7628) was merged, fixing the above mentioned issue.
cc: @chipzoller @realshuting

test: create-authorizationpolicy

---

other/advanced-restrict-image-registries/01-assert.yaml
other/advanced-restrict-image-registries/01-enforce.yaml
other/advanced-restrict-image-registries/02-setup.yaml
other/advanced-restrict-image-registries/03-pods.yaml
other/advanced-restrict-image-registries/99-delete.yaml
other/advanced-restrict-image-registries/pod-bad.yaml
other/advanced-restrict-image-registries/pod-good.yaml
other/advanced-restrict-image-registries/podcontroller-bad.yaml
other/advanced-restrict-image-registries/podcontroller-good.yaml
other/allowed-base-images/01-assert.yaml
other/allowed-base-images/01-enforce.yaml
other/allowed-base-images/02-setup-cm.yaml
other/allowed-base-images/03-manifests.yaml
other/allowed-base-images/99-delete.yaml
other/allowed-base-images/pod-bad.yaml
other/allowed-base-images/pod-good.yaml
other/allowed-base-images/podcontroller-bad.yaml
other/allowed-base-images/podcontroller-good.yaml
other/ensure-production-matches-staging/01-policy.yaml
other/ensure-production-matches-staging/02-manifests.yaml
other/ensure-production-matches-staging/03-prod.yaml
other/ensure-production-matches-staging/deploy-bad-image.yaml
other/ensure-production-matches-staging/deploy-bad-imversion.yaml
other/ensure-production-matches-staging/deploy-bad-name.yaml
other/ensure-production-matches-staging/deploy-good.yaml
other/ensure-production-matches-staging/deployments.yaml
other/ensure-production-matches-staging/ns.yaml
other/ensure-production-matches-staging/policy-ready.yaml

#546 
Contains 3 tests that tests the checkpoint bug fix.

feat: 3 tests in others following checkpoint bug fix

---

other/restrict-jobs/artifacthub-pkg.yml
other/restrict-jobs/cronjob.yaml
other/restrict-jobs/job.yaml
other/restrict-jobs/restrict-jobs.yaml

add Restrict Jobs

---

openshift/enforce-etcd-encryption/artifacthub-pkg.yml
openshift/enforce-etcd-encryption/enforce-etcd-encryption.yaml
openshift/inject-infrastructurename/artifacthub-pkg.yml
openshift/inject-infrastructurename/inject-infrastructurename.yaml

* Adds Inject Infrastructure Name sample
* Fixes a small misspelling in another policy's description

Openshift machineset

---

.github/workflows/test.yml
other/block-large-images/bad.yaml
other/block-large-images/podcontrollers-bad.yaml
other/block-large-images/pods-bad.yaml
other/block-stale-images/99-delete.yaml
other/check-nvidia-gpu/good01.yaml
other/check-nvidia-gpu/good03.yaml
other/check-nvidia-gpu/podcontrollers-bad.yaml
other/check-nvidia-gpu/podcontrollers-good.yaml
other/check-nvidia-gpu/pods-bad.yaml
other/check-nvidia-gpu/pods-good.yaml

#546 
Splits kuttl test workflows into categories.

feat: kuttl tests split category-wise

---

best-practices/check-deprecated-apis/artifacthub-pkg.yml
best-practices/check-deprecated-apis/check-deprecated-apis.yaml
best-practices/check-deprecated-apis/kyverno-test.yaml
best-practices/check-deprecated-apis/resource.yaml

rm: validate-1-22 rule from check-dep-apis

---

pod-security/enforce/kustomization.yaml
pod-security/kustomization.yaml
pod-security/restricted/kustomization.yaml

Signed-off-by: Alok N <alokme123@gmail.com>
----------
#669

fix deprecated command bases with resources (cherry-pick #686)

---

CRDs/machineset.yaml

Adds the OpenShift MachineSet CRD for future kuttl tests.

add MachineSet CRD

---

CRDs/machineset.yaml

add MachineSet CRD (cherry-pick #697)

---

other/b-d/cordon-and-drain-node/artifacthub-pkg.yml
other/b-d/cordon-and-drain-node/cordon-and-drain-node.yaml
other/e-l/forbid-cpu-limits/01-assert.yaml
other/e-l/forbid-cpu-limits/01-enforce.yaml
other/e-l/forbid-cpu-limits/02-manifests.yaml
other/e-l/forbid-cpu-limits/99-delete.yaml
other/e-l/forbid-cpu-limits/artifacthub-pkg.yml
other/e-l/forbid-cpu-limits/forbid-cpu-limits.yaml
other/e-l/forbid-cpu-limits/kyverno-test.yaml
other/e-l/forbid-cpu-limits/podcontrollers-bad.yaml
other/e-l/forbid-cpu-limits/podcontrollers-good.yaml
other/e-l/forbid-cpu-limits/pods-bad.yaml
other/e-l/forbid-cpu-limits/pods-good.yaml
other/e-l/forbid-cpu-limits/resource.yaml
other/res/restrict-ingress-host/02-manifests.yaml
other/res/restrict-ingress-host/ingress-updates-bad.yaml
other/res/restrict-ingress-host/ingress-updates-good.yaml
other/res/restrict-ingress-host/kyverno-test.yaml
other/res/restrict-ingress-host/resource.yaml
other/res/restrict-ingress-host/restrict-ingress-host.yaml
other/res/restrict-ingress-host/values.yaml

* add forbid-cpu-limits and tests
* add cordon-and-drain
* add minversion annotation
* add new rule to restrict-ingress-host just for UPDATEs
---------

Add 2 samples, fix one (cherry-pick #704)

---

.github/workflows/test.yml

Uses `kyverno/action-install-cli` to install the latest version of Kyverno for KUTTL test workflow.

feat: use kyverno/action-install-cli for kuttl test workflow

---

other/rec-req/require-image-source/values.yaml

Removes a duplicate key in a variable values file to unblock development in kyverno/kyverno for a feature which impacts the test manifest layout.

remove duplicate imageData key

---

karpenter/set-karpenter-non-cpu-limits/pod-ephemeral-storage-patched1.yaml
karpenter/set-karpenter-non-cpu-limits/pod-ephemeral-storage-patched2.yaml
other/a/add-volume-deployment/resource.yaml

This PR fixes incorrect patched resources in tests.

fix: incorrect patched resources in tests

---

kubevirt/add-services/generated-svc.yaml
kubevirt/add-services/generatedResource.yaml

This PR fixes incorrect generated resources in tests.

fix: incorrect generated resources in tests

---

karpenter/set-karpenter-non-cpu-limits/pod-memory-patched1.yaml
karpenter/set-karpenter-non-cpu-limits/pod-memory-patched2.yaml
other/a/always-pull-images/patched-pod02.yaml
other/a/always-pull-images/patchedResource2.yaml
other/a/always-pull-images/resource.yaml
other/e-l/inject-sidecar-deployment/patchedResource2.yaml

This PR fixes a couple mutation tests expected resources.

fix: mutation tests expected resources

---

other/a/always-pull-images/patched-pod02.yaml

fix: kuttl test

---

.github/workflows/check-actions.yaml
.github/workflows/ci.yml
.github/workflows/test.yml

This PR ensures usage of pinned actions.

chore: ensure usage of pinned actions

---

.github/workflows/ci.yml
.github/workflows/test.yml

This PR fixes workflow permissions and concurrency.

chore: fix workflow perms and concurrency

---

artifacthub-repo.yml

This PR adds myself in artifacthub owners.
cc @JimBugwadia @realshuting

chore: add myself in artifacthub owners

---

.github/cherry-pick-bot.yml

This PR enables cherry pick bot.

chore: enable cherry pick bot

---

.hack/update-artifacthub-pkg.sh
pod-security-cel/baseline/disallow-capabilities/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-host-namespaces/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-host-path/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-host-ports-range/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-host-ports/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-host-process/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-privileged-containers/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-proc-mount/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-selinux/artifacthub-pkg.yml
pod-security-cel/baseline/restrict-seccomp/artifacthub-pkg.yml
pod-security-cel/baseline/restrict-sysctls/artifacthub-pkg.yml

fix: artifacthub files

---

.chainsaw.yaml
.github/workflows/check-actions.yaml
.github/workflows/test.yml
cert-manager/limit-dnsnames/01-enforce.yaml
cert-manager/limit-dnsnames/02-manifests.yaml
cert-manager/limit-dnsnames/99-delete.yaml
cert-manager/limit-dnsnames/chainsaw-step-01-assert-1.yaml
cert-manager/limit-dnsnames/chainsaw-step-01-assert-2.yaml
cert-manager/limit-dnsnames/chainsaw-test.yaml
cert-manager/limit-duration/01-enforce.yaml
cert-manager/limit-duration/02-manifests.yaml
cert-manager/limit-duration/99-delete.yaml
cert-manager/limit-duration/chainsaw-step-01-assert-1.yaml
cert-manager/limit-duration/chainsaw-step-01-assert-2.yaml
cert-manager/limit-duration/chainsaw-test.yaml
cert-manager/restrict-issuer/01-enforce.yaml
cert-manager/restrict-issuer/02-manifests.yaml
cert-manager/restrict-issuer/99-delete.yaml
cert-manager/restrict-issuer/chainsaw-step-01-assert-1.yaml
cert-manager/restrict-issuer/chainsaw-step-01-assert-2.yaml
cert-manager/restrict-issuer/chainsaw-test.yaml
kuttl-test.yaml

chore: migrate tests to chainsaw

---

pod-security-cel/baseline/disallow-privileged-containers/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-privileged-containers/disallow-privileged-containers.yaml
pod-security-cel/baseline/disallow-proc-mount/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-proc-mount/disallow-proc-mount.yaml
pod-security-cel/baseline/disallow-selinux/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-selinux/disallow-selinux.yaml
pod-security-cel/baseline/restrict-seccomp/artifacthub-pkg.yml
pod-security-cel/baseline/restrict-seccomp/restrict-seccomp.yaml
pod-security-cel/baseline/restrict-sysctls/artifacthub-pkg.yml
pod-security-cel/baseline/restrict-sysctls/restrict-sysctls.yaml

Closes #843
Add the annotation `policies.kyverno.io/minversion` to PSS CEL policies.

fix: add the annotation policies.kyverno.io/minversion to CEL policies

---

best-practices/disallow-cri-sock-mount/.chainsaw-test/pod-containerd-sock.yaml
best-practices/disallow-cri-sock-mount/.chainsaw-test/pod-crio-sock.yaml
best-practices/disallow-cri-sock-mount/artifacthub-pkg.yml
best-practices/disallow-cri-sock-mount/disallow-cri-sock-mount.yaml
cleanup/cleanup-empty-replicasets/artifacthub-pkg.yml
cleanup/cleanup-empty-replicasets/cleanup-empty-replicasets.yaml
other/memory-requests-equal-limits/artifacthub-pkg.yml
other/memory-requests-equal-limits/memory-requests-equal-limits.yaml
other/refresh-env-var-in-pod/.chainsaw-test/chainsaw-step-04-apply-1.yaml
other/refresh-env-var-in-pod/.chainsaw-test/chainsaw-test.yaml
other/require-emptydir-requests-limits/.chainsaw-test/chainsaw-test.yaml
other/require-emptydir-requests-limits/.chainsaw-test/pod-good.yaml
other/require-emptydir-requests-limits/.chainsaw-test/podcontroller-bad.yaml
other/require-emptydir-requests-limits/artifacthub-pkg.yml
other/require-emptydir-requests-limits/require-emptydir-requests-limits.yaml
other/resolve-image-to-digest/.chainsaw-test/podcontroller-patched.yaml
other/resolve-image-to-digest/.chainsaw-test/pods-patched.yaml
pod-security-cel/baseline/disallow-host-ports-range/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-host-ports-range/disallow-host-ports-range.yaml
pod-security/baseline/disallow-host-ports-range/artifacthub-pkg.yml
pod-security/baseline/disallow-host-ports-range/disallow-host-ports-range.yaml

Closes #482
Fixes #781 
Partially addresses #842 
Fixes #808 
Fixes #799 
Adds a cleanup policy to remove empty ReplicaSets.
Fixes some values in Chainsaw tests.
Reworks Require Requests and Limits for emptyDir
Policy fixes

Misc policy updates

---

other/resolve-image-to-digest/.chainsaw-test/podcontroller-patched.yaml
other/resolve-image-to-digest/.chainsaw-test/pods-patched.yaml

fix: busybox image digest

---

cleanup/cleanup-bare-pods/artifacthub-pkg.yml
cleanup/cleanup-bare-pods/cleanup-bare-pods.yaml
cleanup/cleanup-empty-replicasets/artifacthub-pkg.yml
cleanup/cleanup-empty-replicasets/cleanup-empty-replicasets.yaml
other/copy-namespace-labels/artifacthub-pkg.yml
other/copy-namespace-labels/copy-namespace-labels.yaml
other/require-image-source/.chainsaw-test/pod-bad.yaml
other/require-image-source/.chainsaw-test/podcontroller-bad.yaml
other/require-imagepullsecrets/.chainsaw-test/pod-bad.yaml
other/require-imagepullsecrets/.chainsaw-test/pod-good.yaml
other/require-imagepullsecrets/.chainsaw-test/podcontroller-bad.yaml
other/require-imagepullsecrets/.chainsaw-test/podcontroller-good.yaml
other/require-imagepullsecrets/.kyverno-test/resource.yaml

Adds new sample policies and fixes tests as a result of changes to test images outside the Kyverno org.

Sample policies

---

other/resolve-image-to-digest/.chainsaw-test/podcontroller-patched.yaml
other/resolve-image-to-digest/.chainsaw-test/podcontroller.yaml
other/resolve-image-to-digest/.chainsaw-test/pods-patched.yaml
other/resolve-image-to-digest/.chainsaw-test/pods.yaml

Use old busybox to fix digest changing.

fix: use old busybox to fix digest changing

---

other/restrict-scale/artifacthub-pkg.yml
other/restrict-scale/restrict-scale.yaml

use conditional anchor instead of equality for restrict-scale

fix: use conditional anchor instead of equality for restrict-scale

---

psa/add-psa-namespace-reporting/.chainsaw-test/chainsaw-test.yaml
psa/add-psa-namespace-reporting/.chainsaw-test/namespace-with-psa-labels.yaml
psa/add-psa-namespace-reporting/.chainsaw-test/namespace-without-psa-labels.yaml
psa/add-psa-namespace-reporting/.chainsaw-test/policy-ready.yaml
psa/add-psa-namespace-reporting/.kyverno-test/kyverno-test.yaml
psa/add-psa-namespace-reporting/.kyverno-test/namespace-with-psa-labels.yaml
psa/add-psa-namespace-reporting/.kyverno-test/namespace-without-psa-labels.yaml
psa/add-psa-namespace-reporting/add-psa-namespace-reporting.yaml
psa/add-psa-namespace-reporting/artifacthub-pkg.yml

Closes https://github.com/kyverno/policies/issues/868
This PR will add Policy Add PSA Namespace Reporting

Add psa namespace reporting

---

psa/add-psa-namespace-reporting/artifacthub-pkg.yml

A fix from previous PR #877
Fixes the date formatting in the `createdAt` field in `artifacthub-pkg.yml` file.

Fix createdAt timestamp in artifacthub-pkg.yml

---

other/restrict-sa-automount-sa-token/artifacthub-pkg.yaml

Fixes an indentation issue created by PR #881 I didn't catch.
Fixes metadata indentation.

fix indentation

---

other/deny-secret-service-account-token-type/.chainsaw-test/bad-secret.yaml
other/deny-secret-service-account-token-type/.chainsaw-test/chainsaw-step-01-assert-1.yaml
other/deny-secret-service-account-token-type/.chainsaw-test/chainsaw-test.yaml
other/deny-secret-service-account-token-type/.chainsaw-test/good-secret.yaml
other/deny-secret-service-account-token-type/.kyverno-test/kyverno-test.yaml
other/deny-secret-service-account-token-type/.kyverno-test/resource.yaml
other/deny-secret-service-account-token-type/artifacthub-pkg.yaml
other/deny-secret-service-account-token-type/deny-secret-service-account-token-type.yaml

partially closes #819 
added a sample policy to Deny Secret Service Account Token Type

Deny Secret Service Account Token Type

---

kubecost/kubecost-proactive-cost-control/artifacthub-pkg.yml
kubecost/kubecost-proactive-cost-control/kubecost-proactive-cost-control.yaml

N/A
Adds a new policy called Kubecost Proactive Cost Control

add Kubecost Proactive Cost Control

---

README.md
best-practices/add-rolebinding/.chainsaw-test/chainsaw-test.yaml
other/block-cluster-admin-from-ns/.chainsaw-test/chainsaw-test.yaml
other/block-updates-deletes/.chainsaw-test/chainsaw-test.yaml
other/check-serviceaccount/.chainsaw-test/chainsaw-test.yaml
other/check-subjectaccessreview/.chainsaw-test/chainsaw-test.yaml
other/inspect-csr/.chainsaw-test/chainsaw-test.yaml
other/limit-configmap-for-sa/.chainsaw-test/chainsaw-test.yaml
psa/deny-privileged-profile/.chainsaw-test/chainsaw-test.yaml

Fix context issue with chainsaw v0.1.6.

fix: context issue with chainsaw v0.1.6

---

other/block-stale-images/.chainsaw-test/podcontrollers-good.yaml
other/block-stale-images/.chainsaw-test/pods-good.yaml

n/a
Update image used to one that is regularly updated, to avoid test failures

update image to one that is updated regularly

---

.github/workflows/test.yml
other/record-creation-details/.chainsaw-test/chainsaw-test.yaml

fix: use cluster version binding

---

.github/ISSUE_TEMPLATE/bug_report.yml

Bumps version numbers in bug report issue template.

Bump versions in bug issue template

---

pod-security-cel/restricted/require-run-as-nonroot/artifacthub-pkg.yml
pod-security-cel/restricted/require-run-as-nonroot/require-run-as-nonroot.yaml

Updating the incorrect rule name

Update the incorrect rulename

---

other/check-vpa-configuration/.chainsaw-test/bad.yaml
other/check-vpa-configuration/.chainsaw-test/chainsaw-step-01-assert-1.yaml
other/check-vpa-configuration/.chainsaw-test/chainsaw-test.yaml
other/check-vpa-configuration/.chainsaw-test/good.yaml
other/check-vpa-configuration/.chainsaw-test/prereq.yaml
other/check-vpa-configuration/artifact-hub.yaml
other/check-vpa-configuration/check-vpa-configuration.yaml

closes #929 
added a policy to check if vpa is configured or not

added a policy to check if vpa is configured or not

---

other/require-replicas-allow-disruption/artifact-hub.yaml
other/require-replicas-allow-disruption/require-replicas-allow-disruption.yaml

None. If I need to create an issue, please leave a hint and I will create one.
- StatefulSet wasn't mentioned in artifact-hub.yaml
- Previous description stated problems if minAvailable is lower than the replica definition, but the opposite is true.
-  I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended. <-- _I only changed documentation._
-  I have added the artifacthub-pkg.yml file and have verified it is complete and correct. <-- _I only changed documentation._

Improve policy description

---

kasten/kasten-3-2-1-backup/artifacthub-pkg.yml
kasten/kasten-3-2-1-backup/kasten-3-2-1-backup.yaml
kasten/kasten-data-protection-by-label/artifacthub-pkg.yml
kasten/kasten-data-protection-by-label/kasten-data-protection-by-label.yaml
kasten/kasten-generate-policy-by-preset-label/artifacthub-pkg.yml
kasten/kasten-generate-policy-by-preset-label/kasten-generate-policy-by-preset-label.yaml

Fixes block scalar indentation issues causing build failures.

Fix indentation issues

---

other/verify-image-with-multi-keys/artifacthub-pkg.yml
other/verify-image-with-multi-keys/verify-image-with-multi-keys.yaml

Fixed typo for the 'keys' ConfigMap name

---

.github/actions/run-tests/action.yaml

chore: bump chainsaw

---

.chainsaw.yaml
.github/workflows/test.yml

chore: bump chainsaw (cherry-pick #1104)

chore: bump chainsaw (cherry-pick #1104)

---

README.md

Adds a small note in the contribution guide on generating digests for a policy.

add note about digest generation

---

.github/workflows/check-codegen.yml

Verify e2e workflow is up to date in CI.

chore: verify e2e workflow is up to date in CI

---

.github/dependabot.yml

Update dependabot to update actions.

chore: update dependabot to update actions

---

best-practices/add-rolebinding/.chainsaw-test/chainsaw-step-00-apply-1.yaml

https://github.com/kyverno/kyverno/pull/10963

fix: aggregate clusterrole to admission controller

---

.github/actions/run-tests/action.yaml
other/deployment-replicas-higher-than-pdb/.chainsaw-test/good-pdb.yaml
other/prevent-cr8escape/.chainsaw-test/pods-good.yaml
other/prevent-cr8escape/artifacthub-pkg.yml
other/prevent-cr8escape/prevent-cr8escape.yaml
other/require-ingress-https/.chainsaw-test/ingress-bad.yaml
other/require-ingress-https/.chainsaw-test/ingress-good.yaml
other/require-ingress-https/.kyverno-test/resource.yaml
other/restrict-ingress-classes/.chainsaw-test/ingress-bad.yaml
other/restrict-ingress-classes/.chainsaw-test/ingress-good.yaml
other/restrict-ingress-defaultbackend/.chainsaw-test/ingress-good.yaml
other/restrict-ingress-host/.chainsaw-test/ingress-bad.yaml
other/restrict-ingress-host/.chainsaw-test/ingress-good.yaml
other/restrict-ingress-host/.chainsaw-test/ingress-updates-bad.yaml
other/restrict-ingress-host/.chainsaw-test/ingress-updates-good.yaml
other/restrict-ingress-host/.chainsaw-test/ingress.yaml
other/restrict-ingress-wildcard/.chainsaw-test/ingress-bad.yaml
other/restrict-ingress-wildcard/.chainsaw-test/ingress-good.yaml
other/restrict-node-affinity/.chainsaw-test/pod-good.yaml
other/restrict-node-affinity/.chainsaw-test/podcontroller-good.yaml
other/restrict-node-label-changes/.chainsaw-test/chainsaw-test.yaml

feat: bump chainsaw

---

.github/actions/run-tests/action.yaml

chore: verify chainsaw with cosign

---

.github/workflows/test.yml
.hack/chainsaw-matrix/workflow.yaml

chore: fix ci jobs

---

.github/workflows/cel-test.yml
.github/workflows/check-actions.yaml
.github/workflows/check-codegen.yml
.github/workflows/ci.yml
.github/workflows/test.yml
.hack/chainsaw-matrix/workflow.yaml

chore: fix ci

---

cleanup/cleanup-bare-pods/.chainsaw-test/chainsaw-test.yaml
cleanup/cleanup-empty-replicasets/.chainsaw-test/chainsaw-test.yaml
flux-cel/verify-git-repositories/.chainsaw-test-rename-after-issue-10313-fix/chainsaw-test-rename-after-issue-10313-fix.yaml
flux/verify-flux-images/.chainsaw-test/chainsaw-test.yaml
flux/verify-git-repositories/.chainsaw-test/chainsaw-test.yaml
other/check-serviceaccount-secrets/.chainsaw-test/chainsaw-test.yaml
other/check-vpa-configuration/.chainsaw-test/chainsaw-test.yaml
other/copy-namespace-labels/.chainsaw-test/chainsaw-test.yaml
other/deployment-replicas-higher-than-pdb/.chainsaw-test/chainsaw-test.yaml
other/pdb-maxunavailable-with-deployments/.chainsaw-test/chainsaw-test.yaml
other/replace-image-registry-with-harbor/.chainsaw-test/chainsaw-test.yaml
other/require-reasonable-pdbs/.chainsaw-test/chainsaw-test.yaml
other/require-replicas-allow-disruption/.chainsaw-test/chainsaw-test.yaml
other/resource-creation-updating-denied/.chainsaw-test/chainsaw-test.yaml
other/restrict-clusterrole-csr/.chainsaw-test/chainsaw-test.yaml

Add missing chainsaw test schemas.

chore: add missing chainsaw test schemas

---

other/verify-image-ivpol/.chainsaw-test/bad.yaml
other/verify-image-ivpol/.chainsaw-test/chainsaw-test.yaml
other/verify-image-ivpol/.chainsaw-test/good.yaml
other/verify-image-ivpol/.chainsaw-test/policy-ready.yaml
other/verify-image-ivpol/artifacthub-pkg.yml
other/verify-image-ivpol/verify-image-ivpol.yaml

This is a sample policy for `ImageValidatingPolicy`.  
https://github.com/kyverno/kyverno/issues/12085

verify-image-ivpol

---

.github/workflows/test.yml
flux/verify-flux-images/.chainsaw-test/chainsaw-test.yaml

Makes the SED command work on ubuntu and MacOS as well

Update K8s version metrix

---

.github/ISSUE_TEMPLATE/bug_report.yml

Update bug_report.yml issue template

---

.github/ISSUE_TEMPLATE/bug_report.yml

As discussed in previous PR, it makes sense to bump version once more https://github.com/kyverno/policies/pull/1314#issuecomment-3236945476
K8s 1.34 is about to be released or already live, so I think it makes sense to add it.
Fix #1313
Updates Issue template versions to latest

Update bug_report.yml issue template to latest versions
