best-practices/require_labels/require_labels.yaml

Hi, the description on the "require-labels" policy was the one for image tags. With this PR an alternative description is suggested. 
The sentences used are copied from https://kubernetes.io/docs/concepts/configuration/overview/#using-labels and https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
Would this be an appropriate description for this policy?

replaces description for the require-labels policy

---

other/restrict-service-account.yaml

Related to https://github.com/kyverno/kyverno/issues/1619
I did a few tests and this approach seems straightforward to me - not sure if there are any gotchas. Notice that the first rule could be optional but in a real-world scenario, I'd like to have it in place to prevent that the pod could be created by a controller using the default service account. We may consider removing the first rule to keep the sample more concise. I'm intentionally leaving init containers out of scope.

add restrict-service-account sample policy

---

best-practices/require_drop_all/require_drop_all.yaml
other/restrict_annotations.yaml
other/restrict_controlplane_scheduling.yaml
other/restrict_node_label_changes.yaml
other/restrict_node_selection.yaml

This PR adds four new sample policies:
* Restrict node label changes
* Restrict node selection
* Restrict control plane scheduling
* Restrict Annotations
It also fixes the `require_drop_all.yaml` policy based on #22

Add node restriction and annotation policies; fix sample

---

best-practices/disallow_helm_tiller/disallow_helm_tiller.yaml
best-practices/restrict_image_registries/restrict_image_registries.yaml
other/restrict_annotations.yaml
other/restrict_ingress_host.yaml
other/restrict_pod_count_per_node.yaml
other/restrict_service_account.yaml
pod-security/default/restrict-apparmor-profiles/restrict-apparmor-profiles.yaml

Adds a new annotation to relevant policies called `policies.kyverno.io/minversion` which notes the minimum version of Kyverno needed to implement the policy. This will get complimented by the `render` program in the kyverno/website repo so the annotation is scraped and presented as a filter category on the /policies page.

add policies.kyverno.io/minversion annotations

---

pod-security/restricted/require-non-root-groups/require-non-root-groups.yaml

change the policy require-non-root-groups to allow fsGroup values greater than zero

fix #47: allow fsGroup values greater than zero

---

pod-security/baseline/disallow-adding-capabilities/disallow-adding-capabilities.yaml

When `add` is specified as `null` instead of `"null"` the policy is not
actually enforced.
Fixes #69

Fix capabilities.add of null => "null"

---

other/ensure_probes_different.yaml

Fixes the inverted check so now it's correct.

fix deny logic

---

best-practices/disallow_cri_sock_mount/test.yaml

Signed-off-by: viveksahu26 <vivekkumarsahu650@gmail.com>
Description
In this [policy](https://github.com/kyverno/policies/blob/main/best-practices/disallow_cri_sock_mount/disallow_cri_sock_mount.yaml) 3 rules are present i.e `validate-docker-sock-mount`, `validate-containerd-sock-mount` and `validate-crio-sock-mount`. Since, the policy validates for 3 rules against the [resource](https://github.com/kyverno/policies/blob/main/best-practices/disallow_cri_sock_mount/resource.yaml). So, there should be 3 result present in the [test.yaml](https://github.com/kyverno/policies/blob/main/best-practices/disallow_cri_sock_mount/test.yaml). But in the test.yaml file result of only 2 rules are present.
Solution:-
We also need to add result for 3rd rule in the test.yaml file.

Added result in the test.yaml file for rule validate-crio-sock-mount

---

best-practices/restrict_image_registries/test.yaml

According to this policy https://github.com/kyverno/policies/blob/ef49652730b807f70d483dc74ef52fcff8a41194/best-practices/restrict_image_registries/restrict_image_registries.yaml#L31
The result should be `fail` as the image is from `ghcr.io`.

Fix the result for restrict-image-registries

---

README.md

Hi Kyverno folks, I noticed these links weren't working in the README and I believe it's because of the anchor tags, thanks.

Fix README anchor tags

---

other/pod_lifetime_annotation/enforce_pod_duration.yaml

Signed-off-by: Trey Dockendorf <tdockendorf@osc.edu>
> /kind bug
Noticed these warnings when running tests from Kyverno:
```
Executing pod-lifetime...
applying 1 policy to 2 resources... 
I1103 15:52:36.821740    3439 operator.go:70] EngineValidate "msg"="DEPRECATED: The Duration* operators have been replaced with the other existing operators that now also support duration values" "kind"="Pod" "name"="test-lifetime-pass" "namespace"="test" "policy"="pod-lifetime" "rule"="pods-lifetime" "operator"="durationgreaterthan"
I1103 15:52:36.822442    3439 operator.go:70] EngineValidate "msg"="DEPRECATED: The Duration* operators have been replaced with the other existing operators that now also support duration values" "kind"="Pod" "name"="test-lifetime-fail" "namespace"="test" …
```

Update lifetime policy to remove deprecated Duration* operator

---

.github/dependabot.yml
.github/workflows/ci.yml

n/a
n/a
> /kind feature
Use github actions to test the policies (also use dependabot to keep actions up to date)
Note this did reveal that one of the policies doesn't pass against the current release cli, it does pass in v1.5.2-rc1 though.
I could make this pull the latest pre-release if one exists, but that feels a bit fragile, ideally the policies repo should match what the current release can do?
n/a

Test policy in pr

---

other/require_unique_uid_per_workload/require_unique_uid_per_workload.yaml

Hi all 👋,
I've been trying to write a policy that only allows cluster-unique UIDs per Workload. More details below:
/kind feature
Add a policy that only allows cluster-unique UIDs per workload.
Apply the Policy (set on enforce):
```
$ kubectl create -f require_unique_uid_per_workload.yaml
```
Create a deployment which shall `runAsUser` 1337
```
$ cat << 'EOF' | kubectl create -f - 
apiVersion: apps/v1
kind: Deployment
metadata:
labels:
app: server-1
name: server-1
spec:
replicas: 1
selector:
matchLabels:
app: server-1
template:
metadata:
labels:
app: server-1
spec:
containers:
- image: nginxinc/nginx-unprivileged
name: hello-1
securityContext:
runAsUser: 1337
resources: {}
EOF
```
Observe that a pod can be created.
Create another deployment `server-2` which shall `runAsUser` 1337.
```
$ …
```

Adds policy that only allows cluster-unique UIDs per Workload

---

cert-manager/limit-duration/limit-duration.yaml
other/add_node_affinity/add_node_affinity.yaml
other/disable_automountserviceaccounttoken/disable-automountserviceaccounttoken.yaml
other/disallow_all_secrets/disallow_all_secrets.yaml
other/prepend_image_registry/prepend_image_registry.yaml
other/require_unique_external_dns/require_unique_external_dns.yaml
other/require_unique_uid_per_workload/require_unique_uid_per_workload.yaml
traefik/disallow_default_tlsoptions/disallow_default_tlsoptions.yaml

Closes #177 
Closes #187 
Closes #188 
Closes #190 
Adds new policies:
* Add Node Affinity
* Disable Automount ServiceAccount Token
* Disallow All Secrets
* Require Unique External DNS
* Disallow Default TLSOption (for Traefik)
This PR adds new policies as linked and makes corrections and normalizations to others.

New sample policies

---

other/block-velero-restore/block-velero-restore.yaml
other/block-velero-restore/kyverno-test.yaml
other/block-velero-restore/resource.yaml

/kind documentation
Example policy for blocking Velero Restore operation into protected or system namespaces.

feat: add block velero restore example policy

---

other/verify_image_gcpkms.yaml
other/verify_image_k8s.yaml

feat: add two new verify image policies
We forgot to add match: keyword.
cc: @chipzoller

fix: forget to add match keyword

---

other/add-default-securitycontext/add-default-securitycontext.yaml
other/add-default-securitycontext/patchedResource.yaml

I noticed that we have a check for runAsNonRoot in validation rules but we don't have any mutation for that.
This PR will fix that.
kindly ping @chipzoller
Does it make sense?

feat: add runAsNonRoot:true to default

---

other/limit-hostpath-type-pv/kyverno-test.yaml
other/limit-hostpath-type-pv/limit_hostpath_type_pv.yaml
other/limit-hostpath-type-pv/resource.yaml
other/limit-hostpath-type-pv/variables.yaml

Signed-off-by: eminaktas <eminaktas34@gmail.com>
None
Created a policy for limiting the hostPath type persistent volumes.

add limit hostpath type persistent volume

---

pod-security/baseline/kustomization.yaml

n/a
Remove Kustomization so pod security policies are installed with a default validationFailureAction of audit.

remove patch for validationFailureAction

---

openshift/unique-routes/kyverno-test.yaml
openshift/unique-routes/mock.yaml
openshift/unique-routes/resources.yaml
openshift/unique-routes/unique-routes.yaml

Just as the unique Ingress policy, there should also be the openshift equivalent for route hosts.

add openshift unique route policy

---

openshift/team-validate-ns-name/kyverno-test.yaml
openshift/team-validate-ns-name/resource.yaml
openshift/team-validate-ns-name/team-validate-ns-name.yaml

Adds a policy that validates the name of namespaces/projects created by all authenticated users and only allows namespaces names that start with one of the user's groups followed by a hyphen and something else.
This policy is also great to see how you can work with different JMESpath filters.
I added tests for the policy but I'm not completely sure those make sense since this policy is kind of dynamic in terms of validation (different for each user depending on their groups).

Added team namespace name validation policy

---

other/restrict_ingress_defaultbackend/kyverno-test.yaml
other/restrict_ingress_defaultbackend/resource.yaml
other/restrict_ingress_defaultbackend/restrict_ingress_defaultbackend.yaml

Fixes https://github.com/kyverno/policies/issues/322
Create a sample policy to prevent usage of the Ingress defaultBackend field.

Add other/restrict-ingress-defaultbackend policy 

---

best-practices/check_deprecated_apis.yaml

[3988](https://github.com/kyverno/kyverno/issues/3988)
Closes #331
Fix for `check-deprecated-apis` policy, which causes kyverno to utilise high amount of memory/cpu.
Using wildcard to match `kind` is not necessary and using it on the `apiVersion` much more optimal.. also the pre-conditions had an error which I didn't pick up until i deployed 1.7.0-rc1 but need to remove the `kind` as it should only contain `group` and `apiVersion`.

applying fix to check-deprecated-apis policy

---

other/require-base-image/require-base-image.yaml

Fixes #341 
use type docker-image for buildkit

fix(require-base-image): use type docker-image for buildkit

---

other/restrict_automount_sa_token/kyverno-test.yaml
other/restrict_automount_sa_token/resource.yaml
other/restrict_automount_sa_token/restrict_automount_sa_token.yaml

Signed-off-by: Frank Jogeleit <frank.jogeleit@web.de>
[kyverno/policy-reporter#](https://github.com/kyverno/policy-reporter/issues/155)
Exclude Policy Reporter from Restrict SA automount policy.

Exclude Policy Reporter from 'restrict-automount-sa-token' Policy

---

.github/workflows/ci.yml

Related to #243 
Replace the parsing of environment variables and `git clone` with arguments to the `actions/checkout` action.
The action logs the commit hash as its final output. The last group in the log can be expanded to see the referenced branch. For example, a run on a push to the `release-1.7` branch shows:
```
Checking out the ref
/usr/bin/git checkout --progress --force -B release-1.7 refs/remotes/origin/release-1.7
Switched to a new branch 'release-1.7'
branch 'release-1.7' set up to track 'origin/release-1.7'.
/usr/bin/git log -1 --format='%H'
'db440c1b10d91c29d0e28f279705d248ced5c4a7'
```

Use actions/checkout to clone Kyverno

---

argo/argo-cluster-generation-from-rancher-capi/argo-cluster-generation-from-rancher-capi.yaml

This policy generates and synchronizes Argo CD cluster secrets from Rancher managed cluster CAPI secrets. In this solution, Argo CD integrates with Rancher managed clusters via the central Rancher authentication proxy which shares the network endpoint of the Rancher API/GUI. The policy implements work-arounds for Argo CD issue https://github.com/argoproj/argo-cd/issues/9033 "Cluster-API cluster auto-registration" and Rancher issue https://github.com/rancher/rancher/issues/38053 "Fix type and labels Rancher v2 provisioner specifies when creating CAPI Cluster Secret".
- [n/a] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.

Introduce argo-cluster-generation-from-rancher-capi policy

---

cert-manager/limit-duration/kyverno-test.yaml
cert-manager/limit-duration/resource.yaml

Signed-off-by: viveksahu26 <vivekkumarsahu650@gmail.com>
closes https://github.com/kyverno/policies/issues/355
Variables in the policy whose values in not provided by the  user either through resource file or values file then it will be assigned nil as a value. Therefore, status or result of the policy will be `error`.
/kind bug

updated status/result from skip to error for non-assigned variables

---

kubevirt/k6t-only-instancetype/k6t-require-instancetype.yaml
kubevirt/k6t-only-instancetype/kyverno-test.yaml
kubevirt/k6t-only-instancetype/vm.yaml

Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>
None
Introduces a basic rule in order to enforce the usage of instanceTypes and preferences, and prevents the usage of domain templates in VMs.

KubeVirt: Introduce rule to enforce instanceType usage

---

best-practices/check_deprecated_apis/check_deprecated_apis.yaml

Bumps minimum Kyverno version of check-deprecated-apis to 1.7.4 after bug fix.

update minversion to 1.7.4

---

linkerd/prevent-linkerd-port-skipping/prevent-linkerd-port-skipping.yaml

Adds a new Linkerd policy to prevent Pod port skipping.

add prevent-linkerd-port-skipping

---

best-practices/restrict_node_port/restrict_node_port.yaml

Signed-off-by: André Bauer <monotek@users.noreply.github.com>
* checks "type" only if set otherwise rule will also fail on default, which is "ClusterIP", when the type is not set

check type only if set

---

kubeops/README.md
kubeops/config-syncer-secret-generation-from-rancher-capi/config-syncer-secret-generation-from-rancher-capi.yaml

Closes #418
Implement ClusterPolicy config-syncer-secret-generation-from-rancher-capi.
Note that Kyverno 1.8.0 appears to contain a JMESPath bug that currently prevents this policy from working. Below, please find the contents of the Config Syncer/Kubed Secret generated by this policy. Specifically, notice that the `contexts` json element was rendered incorrectly. This may be due to the fact that the `contexts.context` element is complex. If I change `contexts.context` to be a simple property like `context: metadata.name`, the `contexts` json element renders correctly.
This issue is currently preventing me from using this ClusterPolicy. Please investigate.
```
$ kubectl -n kube-system get secret kubed -o jsonpath='{.data.kubeconfig}' | base64 -d
{
"apiVersion": "v1",
"kind": "Config", …
```

Introduce ClusterPolicy config-syncer-secret-generation-from-rancher-capi

---

other/verify_image_cve-2022-42889.yaml

* Adds check-image-vulns-cve-2022-42889 policy

add check-image-vulns-cve-2022-42889

---

best-practices/require_probes/require_probes.yaml

Signed-off-by: André Bauer <monotek@users.noreply.github.com>
https://github.com/kyverno/kyverno/issues/4983
Make periodSeconds optional so the check works also on the CLI if periodSeconds is not set.
In the cluster periodSeconds has a default of 10 secdonds so the policy would work.

make periodSeconds optional

---

other/require_pdb/kyverno-test.yaml
other/require_pdb/require_pdb.yaml
other/require_pdb/resource-pass.yaml
other/require_pdb/resource-skip.yaml
other/require_pdb/values.yaml

Signed-off-by: André Bauer <andre.bauer@staffbase.com>
* run pdb check only if replicas >= 3 as pdb are usualy not defined for single pod deployments
* also add StatefulSet as resource
* use any in rule
```
kyverno test . 
Executing require-pdb...
applying 1 policy to 2 resources... 
│───│─────────────│─────────────│──────────────────────────────────────│────────│
│ # │ POLICY      │ RULE        │ RESOURCE                             │ RESULT │
│───│─────────────│─────────────│──────────────────────────────────────│────────│
│ 1 │ require-pdb │ require-pdb │ default/Deployment/nginx-deploy-pass │ Pass   │
│ 2 │ require-pdb │ require-pdb │ default/Deployment/nginx-deploy-skip │ Pass   │
│───│─────────────│─────────────│──────────────────────────────────────│────────│
Test Summary: 2 tests …
```

run pdb check only if replicas >= 3

---

kubeops/config-syncer-secret-generation-from-rancher-capi/config-syncer-secret-generation-from-rancher-capi.yaml

Closes #448
Strip '-kubeconfig' suffix from config-syncer cluster name to minimize confusion #448

Strip '-kubeconfig' suffix from config-syncer cluster name to minimize confusion

---

other/restrict-escalation-verbs-roles/kyverno-test.yaml
other/restrict-escalation-verbs-roles/resource.yaml
other/restrict-escalation-verbs-roles/restrict-escalation-verbs-roles.yaml

Fixes #452 
Enhances the `restrict-escalation-verbs-roles` policy so that it only denies RBAC rules that apply to `roles` or `clusterroles` _resources_ in _apiGroup_ `rbac.authorization.k8s.io`. That is, it only forbids Roles or ClusterRoles that can bind, escalate or impersonate Roles or ClusterRoles.
In this enhanced form, it implements CIS Benchmark for Kubernetes 5.1.8.

fix: restrict escalation verbs

---

consul/enforce-min-tls-version/enforce-min-tls-version.yaml
consul/enforce-min-tls-version/kyverno-test.yaml
consul/enforce-min-tls-version/resource.yaml

#446 
We want to create a policy for Consul service mesh to add a policy for the mesh configuration. The policy will check the TLS Min version to ensure that whenever the mesh is configured, there is a minimum version of TLS set for all the service mesh proxies.
cc @shivaylamba

add consul min tls version

---

istio/restrict-virtual-service-wildcard/kyverno-test.yaml
istio/restrict-virtual-service-wildcard/resources.yaml
istio/restrict-virtual-service-wildcard/restrict-virtual-service-wildcard.yaml

no related issue
Adds an example policy that restricts wildcards in the hosts for a VirtualService.

adding a virtual service policy that blocks wildcards

---

best-practices/disallow_default_namespace/disallow_default_namespace.yaml
best-practices/require_drop_all/require_drop_all.yaml
best-practices/require_drop_cap_net_raw/require_drop_cap_net_raw.yaml
other/advertise-node-extended-resources/advertise-node-extended-resources.yaml
other/allowed-image-repos/allowed-image-repos.yaml
other/metadata-match-regex/metadata-match-regex.yaml
other/pdb-maxunavailable/pdb-maxunavailable.yaml
other/pdb-minavailable/pdb-minavailable.yaml
other/policy-for-exceptions/policy-for-exceptions.yaml
other/replace-ingress-hosts/replace-ingress-hosts.yaml
other/require-annotations/require-annotations.yaml
other/require-ingress-https/require-ingress-https.yaml
other/require-unique-service-selector/require-unique-service-selector.yaml
other/require_vuln_scan/require-vulnerability-scan.yaml
other/restrict-edit-for-endpoints/restrict-edit-for-endpoints.yaml
other/restrict-pod-controller-serviceaccount-updates/restrict-pod-controller-serviceaccount-updates.yaml
other/restrict-scale/restrict-scale.yaml
other/verify-image-gcpkms.yaml
other/verify_image.yaml
other/verify_image_cve-2022-42889.yaml
other/verify_image_slsa.yaml
other/verify_image_with_multi_keys.yaml
other/verify_sbom_cyclonedx.yaml
pod-security/restricted/disallow-capabilities-strict/disallow-capabilities-strict.yaml
tekton/verify-tekton-taskrun-vuln-scan/verify-tekton-taskrun-vuln-scan.yaml

Closes #373 
Fixes #440
Fixes #450 
Fixes #457
Closes #478
Closes #479 
Closes #480 
Fixes #483
Adds these new validate policies without tests:
* Allowed Image Repositories
* Metadata Matches Regex
* PodDisruptionBudget maxUnavailable Non-Zero
* Check PodDisruptionBudget minAvailable
* Require Annotations
* Require Ingress HTTPS
* Require Unique Service Selector
* Restrict Edit for Endpoints CVE-2021-25740
* Restrict Pod Controller ServiceAccount Updates
* Verify CycloneDX SBOM (Keyless)
* Verify Image GCP KMS (restored from a previous removal)
* Policy for PolicyExceptions
* Restrict Scale
* Advertise Node Extended Resources
* Replace Ingress Hosts
Updates these policies for attestation changes in Kyverno 1.8.3:
* Verify Image Check CVE-2022-42889
* Require Image Vulnerability Scans
* …

Policy updates for 1.9

---

best-practices/require_probes/resource.yaml
best-practices/restrict_image_registries/resource.yaml
other/disallow_all_secrets/resource.yaml
other/disallow_secrets_from_env_vars/resource.yaml
other/ensure_probes_different/resource.yaml
other/require_pod_priorityclassname/resource.yaml
other/restrict_secrets_by_label/resource.yaml

Part of https://github.com/kubernetes/k8s.io/issues/4780
This PR updates `k8s.gcr.io` to `registry.k8s.io`

Update k8s.gcr.io to registry.k8s.io

---

other/prepend_image_registry/failpatchedResource.yaml
other/prepend_image_registry/patchedResource.yaml
other/prepend_image_registry/patchedResourceWithoutInitContainer.yaml
other/prepend_image_registry/prepend_image_registry.yaml
other/prepend_image_registry/resource.yaml
other/prepend_image_registry/resourceFailed.yaml
other/prepend_image_registry/withoutinitcontainer.yaml

Resolves: #509
Fix the image path for the prepend-registry-initcontainers rule so that it uses the image path for the path instead of the image name. We also update the resources used in the tests to use an image containing a path.

Fix image path for prepend_image_registry policy

---

other/restrict_deprecated_registry/kyverno-test.yaml
other/restrict_deprecated_registry/resource.yaml
other/restrict_deprecated_registry/restrict_deprecated_registry.yaml

N/A
As part of an effort to help the Kubernetes community with the impending registry freeze, mentioned in this [blog post](https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/), I wrote the following example Kyverno policy for this effort. 
The Kyverno policy is used to detect the use of container images that use the now deprecated, soon to be frozen, `k8s.gcr.io` container image registry.
The policy is set to enforce mode, but can be set to audit mode instead.

Restrict deprecated registry

---

other/restrict_node_selection/restrict_node_selection.yaml

The current behaviour is scanning all running pods for the definition of spec.nodename.  
This will always be true, because after the deployment of a pod it is filled with the worker nodename the pod is running at.  
As a result we have many false-positive events.
closes #525 
closes #512 
Closes #529
What we really want to make sure is, that a user is not targeting a specific nodename in it's deployment files at creation time.
This way it is up to the scheduler to choose the best node, especially during rolling updates or renaming of worker nodes.
With adding a precondition to check only on CREATE events we make sure deployed pods are not triggering events anymore.

restrict_node_selection - reduce spec.nodename false-positives

---

other/pdb-maxunavailable/kyverno-test.yaml
other/pdb-maxunavailable/resource.yaml

This PR adds tests for the pdb-maxunavailable policy.

Add tests for pdb-maxunavailable policy

---

velero/block-velero-restore/artifacthub-pkg.yml
velero/block-velero-restore/block-velero-restore.yaml
velero/block-velero-restore/kyverno-test.yaml
velero/block-velero-restore/resource.yaml

Fixes #583
Set default value for namespaceMapping if it doesn't exists
**Note**: I do not possess experience in writing Kyverno policies, please let me know if you think there is a better way to go about the use case of `namespaceMapping` not existing in the Velero restore.

fix: check for empty namespaceMapping in block-velero-restore

---

.github/workflows/ci.yml
argo/application-field-validation/policy-ready.yaml

Reverts the `kind` field of an asserted ClusterPolicy after `render` has been improved to not fail due to kuttl tests.

revert assert policy kind for kuttl fix

---

other/require-storageclass/artifacthub-pkg.yml
other/require-storageclass/kyverno-test.yaml
other/require-storageclass/require-storageclass.yaml
other/require-storageclass/resource.yaml

Fixes #617 
Enhance Require StorageClass policy to only require storageClassName if the StatefulSet has volumeClaimTemplates.

fix: require-storageclass policy

---

other/add-default-resources/kyverno-test.yaml

https://github.com/kyverno/kyverno/issues/6975
use `skip` as a result in `kyverno-test.yaml` as mutation won't occur on `nginx-demo2` because it has both memory and cpu fields.

fix: modify result for add-default-resources

---

other/block-cluster-admin-from-ns/README.md
other/block-cluster-admin-from-ns/artifacthub-pkg.yml
other/block-cluster-admin-from-ns/block-cluster-admin-from-ns.yaml

[x]
In this policy, I’ve told `Kyverno` to look for all user operations (`CREATE, UPDATE, DELETE`), on every object kind, in the testnamespace namespace, and for the `clusterRole cluster-admin`. I’ve also added the `subject User testuser` so it won’t include all the cluster-admins in the cluster.

Added policy - block-cluster-admin-from-ns.yaml

---

kubevirt/README.md
kubevirt/enforce-instancetype/artifacthub-pkg.yml
kubevirt/enforce-instancetype/enforce-instancetype.yaml
kubevirt/enforce-instancetype/kyverno-test.yaml

The policy would previously check for the use of `spec.template.domain` that is not actually invalid when using instance types and preferences.
This change drops that check and replaces it with two validations ensuring both `spec.instancetype.name` and `spec.preference.name` are provided. Any remaining validation being left to the submission webhooks within KubeVirt itself.

kubevirt: Only enforce use of instance types and preferences

---

kubevirt/enforce-instancetype/resource.yaml

Fixing failing policy test for kubevirt: enforce-instancetypes.

fix: kv test fail

---

karpenter/set-karpenter-non-cpu-limits/kyverno-test.yaml
other/add-default-resources/kyverno-test.yaml

https://github.com/kyverno/kyverno/pull/7396
Fix the expected result in the test manifest of policies:
1. add-default-resources
2. set-karpenter-non-cpu-limits

fix: modify test manifest for add-default-resources and set-karpenter-non-cpu-limits

---

pod-security/enforce/kustomization.yaml
pod-security/kustomization.yaml
pod-security/restricted/kustomization.yaml

https://github.com/kubernetes-sigs/kustomize/issues/2243
"bases" command is deprecated since kustomize v2.1.0  in 2019, and replaced by "resources".
https://github.com/kubernetes-sigs/kustomize/blob/661743c7e5bd8c3d9d6866b6bc0a6f0e0b0512eb/site/content/en/blog/releases/v2.1.0.md#resources-expanded-bases-deprecated
``` 
fatal: [localhost]: FAILED! => {"msg": "kustomize command failed with: # Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.\n# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.\n"}
```

fix deprecated kustomization command "bases" with "resources"

---

other/b-d/cordon-and-drain-node/artifacthub-pkg.yml
other/b-d/cordon-and-drain-node/cordon-and-drain-node.yaml
other/e-l/forbid-cpu-limits/01-assert.yaml
other/e-l/forbid-cpu-limits/01-enforce.yaml
other/e-l/forbid-cpu-limits/02-manifests.yaml
other/e-l/forbid-cpu-limits/99-delete.yaml
other/e-l/forbid-cpu-limits/artifacthub-pkg.yml
other/e-l/forbid-cpu-limits/forbid-cpu-limits.yaml
other/e-l/forbid-cpu-limits/kyverno-test.yaml
other/e-l/forbid-cpu-limits/podcontrollers-bad.yaml
other/e-l/forbid-cpu-limits/podcontrollers-good.yaml
other/e-l/forbid-cpu-limits/pods-bad.yaml
other/e-l/forbid-cpu-limits/pods-good.yaml
other/e-l/forbid-cpu-limits/resource.yaml
other/res/restrict-ingress-host/02-manifests.yaml
other/res/restrict-ingress-host/ingress-updates-bad.yaml
other/res/restrict-ingress-host/ingress-updates-good.yaml
other/res/restrict-ingress-host/kyverno-test.yaml
other/res/restrict-ingress-host/resource.yaml
other/res/restrict-ingress-host/restrict-ingress-host.yaml
other/res/restrict-ingress-host/values.yaml

Fixes #702 
Adds two new sample policies, one with kuttl and CLI tests, the other without. Updates restrict-ingress-host with a new rule to match explicitly on UPDATE ops.

Add 2 samples, fix one

---

.github/workflows/test.yml

This PR removes k8s 1.24 and adds k8s 1.28 to the test grid.

chore: remove k8s 1.24 and add k8s 1.28

---

.github/workflows/ci.yml

chore: add actions version

---

.github/workflows/ci.yml

This PR checks test files are up to date.

chore: check test files are up to date

---

other/rec-req/refresh-volumes-in-pods/04-check-annotations.yaml
other/rec-req/refresh-volumes-in-pods/05-check.yaml

This PR attempts to fix the flaky kuttl test `refresh-volumes-in-pods`, ref https://github.com/kyverno/kyverno/issues/8334.
I'm able to consistently reproduce the issue by removing the `sleep 5` command, the tests ran in Kyverno CIs could take longer than 5s. I'm splitting the check step into 2 and adding more delay to see if it helps.
```
]
logger.go:42: 16:43:29 | refresh-volumes-in-pods/4-check | running command: [sh -c val=$(kubectl exec pod01 -n refresh-vols-ns -- cat /mnt/foo/foo)
if [ "$val" = "bar" ]; then exit 0; else exit 1; fi
]
logger.go:42: 16:43:29 | refresh-volumes-in-pods/4-check | command failure, skipping 3 additional commands
case.go:367: failed in step 4-check
case.go:369: exit status 1
```

chore: split kuttl test steps 

---

best-practices/disallow-cri-sock-mount/02-manifests.yaml
best-practices/disallow-cri-sock-mount/artifacthub-pkg.yml
best-practices/disallow-cri-sock-mount/disallow-cri-sock-mount.yaml
best-practices/disallow-cri-sock-mount/pod-cri-dockerd-sock.yaml

N/A
During implementation in our environment, we noted that cri-dockerd was missing from the `disallow-cri-sock-mount` policy. So adding that simple use case in to the existing policy and updating associated test files.

feat: add cri-dockerd flavor to disallow-cri-sock-mount policy

---

.github/workflows/ci.yml
.github/workflows/test.yml

chore: bump golang to 1.21

---

other/e-l/expiration-for-policyexceptions/artifacthub-pkg.yml
other/e-l/expiration-for-policyexceptions/expiration-for-policyexceptions.yaml
other/m-q/policy-for-exceptions/policy-bad.yaml
other/m-q/policy-for-exceptions/policy-good.yaml

None
As a result of [removing the support of v2alpha1 in policy exceptions](https://github.com/kyverno/kyverno/pull/8606), v2beta1 must be used instead.

chore: use v2beta1 in policy exceptions

---

other/m-q/pdb-minavailable/artifacthub-pkg.yml
other/m-q/pdb-minavailable/pdb-minavailable.yaml
other/m-q/pdb-minavailable/ss-good.yaml

Slack-thread: https://kubernetes.slack.com/archives/CLGR9BJU9/p1698916081905549
This PR adds another precondition to `pdb-minavailable-check` policy - to ensure that 0 replicas workloads are not denied by the policy. We added this policy to our clusters and experienced a lot of false-positives on workloads with `replicas: 0`, and no PDBs in namespace. I think this happens because the context variable defaults to 0.

fix(pdb-minavailable-check): ensure correct handling of 0 replicas workloads

---

other/m-q/pdb-minavailable/ss-good.yaml

Fix broken tests after https://github.com/kyverno/policies/pull/800.
It turns out I completely misunderstood the test setup when working on https://github.com/kyverno/policies/pull/800. Sorry about that. 😊 This PR should make the tests do what they are supposed to do.

test(pdb-minavailable-check): fix test-bugs after #800

---

pod-security-cel/baseline/disallow-capabilities/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-host-namespaces/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-host-path/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-host-ports-range/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-host-ports/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-host-process/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-privileged-containers/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-proc-mount/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-selinux/artifacthub-pkg.yml
pod-security-cel/baseline/restrict-seccomp/artifacthub-pkg.yml
pod-security-cel/baseline/restrict-sysctls/artifacthub-pkg.yml

None
CEL PSS policies aren't showing in Artifact Hub because of the duplicate names in the artifacthub-pkg.yml files. This PR adds `-cel` to the name.

fix the name field in artifacthub-pkg.yml for PSS CEL policies

---

other/b-d/create-default-pdb/artifacthub-pkg.yml
other/b-d/create-default-pdb/create-default-pdb.yaml
other/b-d/create-default-pdb/pdb-generated.yaml

Fixes #785 
Copies the Deployment selector into the PDB, instead of assuming the Pod and Deployment labels will be the same

fix: Use Deployment selector for create-default-pdb

---

karpenter/add-karpenter-donot-evict/add-karpenter-donot-evict.yaml
karpenter/add-karpenter-donot-evict/artifacthub-pkg.yml

Fixes #748 
This updates the description for the Karpenter `do-not-evict` policy to clarify that runs that should run uninterrupted to completion will be modified.

Fix: Correct karpenter do-not-evict description

---

other/restrict-sa-automount-sa-token/.chainsaw-test/bad-sa.yaml
other/restrict-sa-automount-sa-token/.chainsaw-test/chainsaw-step-01-assert-1.yaml
other/restrict-sa-automount-sa-token/.chainsaw-test/chainsaw-test.yaml
other/restrict-sa-automount-sa-token/.chainsaw-test/good-sa.yaml
other/restrict-sa-automount-sa-token/.kyverno-test/kyverno-test.yaml
other/restrict-sa-automount-sa-token/.kyverno-test/resource.yaml
other/restrict-sa-automount-sa-token/artifacthub-pkg.yaml
other/restrict-sa-automount-sa-token/restrict-sa-automount-sa-token.yaml

partially addresses #819 
added a policy to Restrict Auto-Mount of Service Account Tokens in Service Account Object

Restrict Auto-Mount of Service Account Tokens in Service Account Object

---

pod-security/baseline/disallow-privileged-containers/artifacthub-pkg.yml
pod-security/baseline/disallow-privileged-containers/disallow-privileged-containers.yaml

`spec.ephemeralContainers[*].securityContext.privileged` is disallowed in [PSS baseline](https://kubernetes.io/docs/concepts/security/pod-security-standards/#baseline) privileged containers. This PR includes this missing field in the validate rule's message

add missing field in disallow-privileged-containers policy message

---

pod-security-cel/restricted/require-run-as-nonroot/.chainsaw-test/chainsaw-test.yaml
pod-security-cel/restricted/require-run-as-nonroot/.kyverno-test/kyverno-test.yaml
pod-security-cel/restricted/require-run-as-nonroot/artifacthub-pkg.yml
pod-security-cel/restricted/require-run-as-nonroot/require-run-as-nonroot.yaml
pod-security/restricted/require-run-as-nonroot/.chainsaw-test/pod-bad.yaml
pod-security/restricted/require-run-as-nonroot/.kyverno-test/resource.yaml

Fixes: #824
Add require-run-as-nonroot policy using CEL expressions.
With the CEL from https://github.com/kyverno/policies/pull/776/commits/853bff9368a3304ad7f6fd8c936c4cbe3fa95132#diff-3416b7bb0c4cce31c5d5833e936ec552ea9d1426fadb6f2ec3b81bce4cb910a8 tests failed when Pod's `spec.securityContext` was  present but `spec.securityContext.runAsNonRoot` was not.

Add require-run-as-nonroot policy that use CEL expressions

---

openshift/disallow-self-provisioner-binding/artifacthub-pkg.yml
openshift/disallow-self-provisioner-binding/disallow-self-provisioner-binding.yaml

PR https://github.com/kyverno/kyverno/pull/9893 was causing this to fail as updates were allowed due to a faulty way of expressing the policy logic. The point of the policy appears to be to forbid updates to this ClusterRoleBinding. This new logic makes that safer and more accurate.

Update OCP policy

---

other/scale-deployment-zero/artifacthub-pkg.yml
other/scale-deployment-zero/scale-deployment-zero.yaml

Closes #949 
To ensure the Scale Deployment to Zero policy functions properly since version 1.10, users must modify Kyverno's ConfigMap by removing or altering the line `excludeGroups: system:nodes` this is added as description.

Updated description of policy

---

other/add-default-resources/add-default-resources.yaml
other/add-default-resources/artifacthub-pkg.yml
other/allowed-base-images/allowed-base-images.yaml
other/allowed-base-images/artifacthub-pkg.yml
psp-migration/add-apparmor/add-apparmor.yaml
psp-migration/add-apparmor/artifacthub-pkg.yml
psp-migration/add-capabilities/add-capabilities.yaml
psp-migration/add-capabilities/artifacthub-pkg.yml

Related to - https://github.com/kyverno/policies/issues/951
Fixes the samples polices described in the issue.

Fixed sample policies to include more container types

---

kasten/kasten-generate-policy-by-preset-label/artifacthub-pkg.yml

Fixes an issue with the Artifact Hub metadata file introduced in PR #1002 which was causing linting checks to fail in CI.

Fix Artifact Hub metadata on Kasten policy

---

other/restrict-wildcard-verbs/.kyverno-test/kyverno-test.yaml
other/restrict-wildcard-verbs/.kyverno-test/resource.yaml
other/restrict-wildcard-verbs/artifacthub-pkg.yml
other/restrict-wildcard-verbs/restrict-wildcard-verbs.yaml

Use the jmespath `to_array` function to better handle nulls on the request.object.rules[] path. In the case of a null a null will be added to an array so the rule can run without error.

Update restrict-wildcard-verbs to handle null/empty rules

---

istio/service-mesh-disallow-capabilities/artifacthub-pkg.yml
istio/service-mesh-require-run-as-nonroot/artifacthub-pkg.yml

Fixes an invalid `createdAt` timestamp introduced in #1043

Fix createdAt time in artifacthub-pkg.yml files

---

.github/workflows/ci.yml

Adds a job to the existing "Policy Test" CI which performs Artifact Hub linting using the official `ah` CLI tool (via container). Job is expected to fail until #1045 is merged.

add Artifact Hub linter as a job

---

pod-security-cel/restricted/restrict-volume-types/.chainsaw-test/chainsaw-test.yaml
pod-security-cel/restricted/restrict-volume-types/.chainsaw-test/ns.yaml
pod-security-cel/restricted/restrict-volume-types/.chainsaw-test/pod-good.yaml
pod-security-cel/restricted/restrict-volume-types/.chainsaw-test/podcontroller-good.yaml
pod-security/restricted/restrict-volume-types/.chainsaw-test/chainsaw-test.yaml
pod-security/restricted/restrict-volume-types/.chainsaw-test/ns.yaml
pod-security/restricted/restrict-volume-types/.chainsaw-test/pod-good.yaml
pod-security/restricted/restrict-volume-types/.chainsaw-test/podcontroller-good.yaml

pod-secuity policies used to hardcode the test namespace as restrict-voltypes-ns to be able to properly delete test resources. This change removes the need to hardcode the namespace name by using the build in namespace binding.
- not applicable
- not applicable

Remove hardcoded test namespace from restrict-volume-types tests

---

.github/kind.yml
pod-security-cel/baseline/disallow-proc-mount/.chainsaw-test/chainsaw-test.yaml
pod-security-cel/baseline/disallow-proc-mount/.chainsaw-test/pod-bad.yaml
pod-security-cel/baseline/disallow-proc-mount/.chainsaw-test/pod-good.yaml
pod-security-cel/baseline/disallow-proc-mount/.chainsaw-test/podcontroller-bad.yaml
pod-security-cel/baseline/disallow-proc-mount/.chainsaw-test/podcontroller-good.yaml
pod-security-cel/baseline/disallow-proc-mount/.chainsaw-test/policy-ready.yaml
pod-security/baseline/disallow-proc-mount/.chainsaw-test/chainsaw-test.yaml
pod-security/baseline/disallow-proc-mount/.chainsaw-test/pod-bad.yaml
pod-security/baseline/disallow-proc-mount/.chainsaw-test/pod-good.yaml
pod-security/baseline/disallow-proc-mount/.chainsaw-test/podcontroller-bad.yaml
pod-security/baseline/disallow-proc-mount/.chainsaw-test/podcontroller-good.yaml
pod-security/baseline/disallow-proc-mount/.chainsaw-test/policy-ready.yaml

Based in the kyverno test resources, this adds chainsaw tests for the pod-security and pod-security-cel policy disallow-proc-mount.
For this to work the kind clusters used for e2e testing need to be created with the `ProcMountType` feature gate enabled as `securityContext.procMount` will be forced to `Default` by the apiserver otherwise.
- not applicable
- not applicable

Add chainsaw tests for pod-security disallow-proc-mount

---

best-practices/require-pod-requests-limits/artifacthub-pkg.yml
best-practices/require-pod-requests-limits/require-pod-requests-limits.yaml

Signed-off-by: Nikhil Maheshwari [nikhil.m2498@gmail.com](mailto:nikhil.m2498@gmail.com)
https://github.com/kyverno/policies/issues/951
This PR updates the existing Kyverno policy to validate CPU and memory resource requests and limits for both containers and initContainers within Pods. This enhancement ensures comprehensive resource management across all container types in a Kubernetes cluster.

Add InitContainers and EphermalContainers to Require Limits and Requests

---

pod-security-cel/baseline/disallow-host-process/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-host-process/disallow-host-process.yaml

Partially Fixes #1058 
Fixes #1095 
I have updated the disallow-host-process policy to include a CEL variable, allContainers, which combines all container types and ensures the hostProcess field is either not set or set to false for each container.

cel expressions of hostprocess containers updated

---

argo/argo-cluster-generation-from-rancher-capi/argo-cluster-generation-from-rancher-capi.yaml
argo/argo-cluster-generation-from-rancher-capi/artifacthub-pkg.yml
kubeops/config-syncer-secret-generation-from-rancher-capi/artifacthub-pkg.yml
kubeops/config-syncer-secret-generation-from-rancher-capi/config-syncer-secret-generation-from-rancher-capi.yaml
other/generate-networkpolicy-existing/artifacthub-pkg.yml
other/generate-networkpolicy-existing/generate-networkpolicy-existing.yaml

https://github.com/kyverno/kyverno/pull/10807
This PR modifies generate policies to make use of `spec.generateExisting` instead of `spec.generateExistingOnPolicyUpdate` as this field is deprecated in 1.10 and will no longer be used.

fix: use generateExisting instead of generateExistingOnPolicyUpdate

---

best-practices/disallow-helm-tiller/.chainsaw-test/bad-deploy.yaml
best-practices/disallow-helm-tiller/.chainsaw-test/bad-pod-fail-first.yaml
best-practices/disallow-helm-tiller/.chainsaw-test/bad-pod-success-first.yaml
best-practices/disallow-helm-tiller/.chainsaw-test/bad-pod.yaml
best-practices/disallow-helm-tiller/.chainsaw-test/good-deploy.yaml
best-practices/disallow-helm-tiller/.chainsaw-test/good-pod.yaml
best-practices/disallow-helm-tiller/.kyverno-test/resource.yaml
best-practices/disallow-helm-tiller/artifacthub-pkg.yml
best-practices/disallow-helm-tiller/disallow-helm-tiller.yaml
best-practices/disallow-latest-tag/.chainsaw-test/bad-pod-latest-fail-first.yaml
best-practices/disallow-latest-tag/.chainsaw-test/bad-pod-latest-success-first.yaml
best-practices/disallow-latest-tag/.chainsaw-test/bad-pod-no-tag.yaml
best-practices/disallow-latest-tag/.chainsaw-test/good-pod.yaml
best-practices/disallow-latest-tag/.kyverno-test/resource.yaml
best-practices/disallow-latest-tag/artifacthub-pkg.yml
best-practices/disallow-latest-tag/disallow-latest-tag.yaml

Partially addresses #951
Updating disallow-helm-tiller and disallow-latest-tag policies to handle all pod types and  test cases to handle initContainers.

Update disallow-helm-tiller and disallow-latest-tag to include all container types in a pod

---

pod-security-cel/baseline/disallow-capabilities/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-capabilities/disallow-capabilities.yaml
pod-security-cel/baseline/disallow-host-namespaces/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-host-namespaces/disallow-host-namespaces.yaml
pod-security-cel/baseline/disallow-host-path/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-host-path/disallow-host-path.yaml
pod-security-cel/baseline/disallow-host-ports-range/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-host-ports-range/disallow-host-ports-range.yaml
pod-security-cel/baseline/disallow-privileged-containers/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-privileged-containers/disallow-privileged-containers.yaml
pod-security-cel/baseline/disallow-proc-mount/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-proc-mount/disallow-proc-mount.yaml
pod-security-cel/baseline/restrict-seccomp/artifacthub-pkg.yml
pod-security-cel/baseline/restrict-seccomp/restrict-seccomp.yaml
pod-security-cel/baseline/restrict-sysctls/artifacthub-pkg.yml
pod-security-cel/baseline/restrict-sysctls/restrict-sysctls.yaml

Closes https://github.com/kyverno/policies/issues/1090
Closes  https://github.com/kyverno/policies/issues/1096
Closes https://github.com/kyverno/policies/issues/1097
Closes https://github.com/kyverno/policies/issues/1091
Closes https://github.com/kyverno/policies/issues/1092
Closes https://github.com/kyverno/policies/issues/1094
Closes https://github.com/kyverno/policies/issues/1099
Closes https://github.com/kyverno/policies/issues/1100
There are redundant expressions in CEL expression to validate the containers, init containers and ephemeral containers in a pod definition. Also the CEL expressions are simplified using variables and optionals
- [] I have added test …

Simplified CEL Expressions for Pod Security (CEL) Baseline policies

---

pod-security-cel/baseline/disallow-selinux/artifacthub-pkg.yml
pod-security-cel/baseline/disallow-selinux/disallow-selinux.yaml

Fixes #1098 
policy updated by using CEL expressions with optional  and variables to ensure SELinux options in Pod security contexts are either unset or set to allowed values

Updated cel expression of selinux

---

other/restrict-node-label-changes/artifacthub-pkg.yml
other/restrict-node-label-changes/restrict-node-label-changes.yaml

Chainsaw test `other/restrict-node-label-changes/restrict-node-label-changes.yaml` broke after PR https://github.com/kyverno/kyverno/pull/10033#issuecomment-2047899999. This PR fixes the test

fix: restrict-node-label-changes chainsaw test

---

other-cel/prevent-cr8escape/.chainsaw-test/pods-good.yaml
other-cel/require-ingress-https/.chainsaw-test/ingress-good.yaml
other-cel/require-ingress-https/.kyverno-test/resource.yaml
other-cel/restrict-ingress-classes/.chainsaw-test/ingress-bad.yaml
other-cel/restrict-ingress-classes/.chainsaw-test/ingress-good.yaml
other-cel/restrict-ingress-defaultbackend/.chainsaw-test/ingress-good.yaml
other-cel/restrict-ingress-wildcard/.chainsaw-test/ingress-bad.yaml
other-cel/restrict-ingress-wildcard/.chainsaw-test/ingress-good.yaml
other-cel/restrict-node-affinity/.chainsaw-test/pod-good.yaml
other-cel/restrict-node-affinity/.chainsaw-test/podcontroller-bad.yaml
other-cel/restrict-node-affinity/.chainsaw-test/podcontroller-good.yaml
other-cel/restrict-node-affinity/.kyverno-test/resource.yaml
tekton-cel/require-tekton-bundle/artifacthub-pkg.yml
tekton-cel/require-tekton-bundle/require-tekton-bundle.yaml

N/A
This PR fixes the test `other-cel/require-ingress-https` as it was failing because of the following error:
```
l.go:52: | 11:40:28 | require-ingress-https | step-02   | CREATE    | WARN  | networking.k8s.io/v1/Ingress @ chainsaw-moral-parrot/goodingress01
=== ERROR
Ingress in version "v1" cannot be handled as a Ingress: strict decoding error: unknown field "spec.rules[0].https"
```

fix: modify the ingress resource

---

other/require-base-image/.chainsaw-test/pod-good.yaml
other/require-base-image/.chainsaw-test/podcontroller-good.yaml
pod-security-cel/restricted/disallow-privilege-escalation/.chainsaw-test/podcontroller-bad.yaml

n/a
Fix tests:
1. Remove image `ghcr.io/samj1912/myapp` that was causing test failures:
```
failed to load data error="failed to fetch image descriptor: ghcr.io/samj1912/myapp:latest, error: failed to fetch image descriptor: ghcr.io/samj1912/myapp:latest, error: failed to fetch image reference: ghcr.io/samj1912/myapp:latest, error: GET https://ghcr.io/token?scope=repository%3Asamj1912%2Fmyapp%3Apull&service=ghcr.io: DENIED: requested access to the resource is denied" logger=DefaultContextLoaderFactory name=imageData
```
2. Fix tests in `pod-security-cel/restricted/disallow-privilege-escalation`.

remove missing image and fix failing tests

---

pod-security-cel/restricted/disallow-privilege-escalation/.chainsaw-test/podcontroller-bad.yaml
pod-security-cel/restricted/disallow-privilege-escalation/artifacthub-pkg.yml
pod-security-cel/restricted/disallow-privilege-escalation/disallow-privilege-escalation.yaml

n/a
The pod security standard restricted mode does not allow a `nil` value for `allowPrivilegeEscalation`. 
It must be set to `false`.
```
securityContext:
allowPrivilegeEscalation: false
```

fix disallow-privilege-escalation policy

---

best-practices-cel/require-drop-cap-net-raw/.chainsaw-test/good-pod.yaml
best-practices-cel/require-drop-cap-net-raw/artifacthub-pkg.yml
best-practices-cel/require-drop-cap-net-raw/require-drop-cap-net-raw.yaml

kyverno should allow the pod with NET_RAW drop capability. It is already fixed for non cel policy.
There is another policy version created with CEL expression which needs to be updated so that the policy is consistent between cel and non cel versions
pod with NET_RAW drop capability is allowed
Closes https://github.com/kyverno/policies/issues/1186

Fix for issue: 1186 CEL expression is updated to support NET_RAW drop capability

---

pod-security-cel/restricted/restrict-seccomp-strict/restrict-seccomp-strict.yaml

Partially addresses #1324 
Refactored restrict-seccomp-strict policy to remove redundancy by replacing `has(...)` checks with optional field access and `.orValue([])` for container lists, keeping container-type–specific validations intact.

restrict-seccomp-strict : simplify CEL expressions

---

pod-security-cel/restricted/disallow-capabilities-strict/disallow-capabilities-strict.yaml

Partially addresses #1324 #1058 
Refactored disallow-capabilities-strict policy to remove redundancy by introducing an `allContainers` CEL variable combining all container types. Updated capability validation to use this variable, ensuring each container drops `ALL` capabilities and only adds `NET_BIND_SERVICE` when specified.

disallow-capabilities-strict : simplify CEL expressions
